/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_fsel_cb.h"
#include "gtk_fsel_dbox.h"
#include "support.h"

GtkWidget*
create_fileselection_1 (void)
{
  GtkWidget *fileselection_1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_1 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_1), "fileselection_1", fileselection_1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_1), 10);

  ok_button1 = GTK_FILE_SELECTION (fileselection_1)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_1), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button1 = GTK_FILE_SELECTION (fileselection_1)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_1), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_1), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_1_show),
                      fileselection_1);
  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel1),
                      fileselection_1);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel1),
                      fileselection_1);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_1), accel_group);

  return fileselection_1;
}

GtkWidget*
create_fileselection_2 (void)
{
  GtkWidget *fileselection_2;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_2 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_2), "fileselection_2", fileselection_2);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_2), 10);

  ok_button2 = GTK_FILE_SELECTION (fileselection_2)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_2), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (fileselection_2)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_2), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_2), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_2_show),
                      fileselection_2);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel2),
                      fileselection_2);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel2),
                      fileselection_2);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_2), accel_group);

  return fileselection_2;
}

GtkWidget*
create_fileselection_3 (void)
{
  GtkWidget *fileselection_3;
  GtkWidget *ok_button3;
  GtkWidget *cancel_button3;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_3 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_3), "fileselection_3", fileselection_3);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_3), 10);

  ok_button3 = GTK_FILE_SELECTION (fileselection_3)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_3), "ok_button3", ok_button3);
  gtk_widget_show (ok_button3);
  GTK_WIDGET_SET_FLAGS (ok_button3, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button3, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button3 = GTK_FILE_SELECTION (fileselection_3)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_3), "cancel_button3", cancel_button3);
  gtk_widget_show (cancel_button3);
  GTK_WIDGET_SET_FLAGS (cancel_button3, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button3, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_3), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_3_show),
                      fileselection_3);
  gtk_signal_connect (GTK_OBJECT (ok_button3), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel3),
                      fileselection_3);
  gtk_signal_connect (GTK_OBJECT (cancel_button3), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel3),
                      fileselection_3);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_3), accel_group);

  return fileselection_3;
}

GtkWidget*
create_fileselection_4 (void)
{
  GtkWidget *fileselection_4;
  GtkWidget *ok_button4;
  GtkWidget *cancel_button4;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_4 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_4), "fileselection_4", fileselection_4);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_4), 10);

  ok_button4 = GTK_FILE_SELECTION (fileselection_4)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_4), "ok_button4", ok_button4);
  gtk_widget_show (ok_button4);
  GTK_WIDGET_SET_FLAGS (ok_button4, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button4, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button4 = GTK_FILE_SELECTION (fileselection_4)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_4), "cancel_button4", cancel_button4);
  gtk_widget_show (cancel_button4);
  GTK_WIDGET_SET_FLAGS (cancel_button4, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button4, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_4), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_4_show),
                      fileselection_4);
  gtk_signal_connect (GTK_OBJECT (ok_button4), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel4),
                      fileselection_4);
  gtk_signal_connect (GTK_OBJECT (cancel_button4), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel4),
                      fileselection_4);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_4), accel_group);

  return fileselection_4;
}

GtkWidget*
create_fileselection_5 (void)
{
  GtkWidget *fileselection_5;
  GtkWidget *ok_button5;
  GtkWidget *cancel_button5;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_5 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_5), "fileselection_5", fileselection_5);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_5), 10);

  ok_button5 = GTK_FILE_SELECTION (fileselection_5)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_5), "ok_button5", ok_button5);
  gtk_widget_show (ok_button5);
  GTK_WIDGET_SET_FLAGS (ok_button5, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button5, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button5 = GTK_FILE_SELECTION (fileselection_5)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_5), "cancel_button5", cancel_button5);
  gtk_widget_show (cancel_button5);
  GTK_WIDGET_SET_FLAGS (cancel_button5, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button5, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_5), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_5_show),
                      fileselection_5);
  gtk_signal_connect (GTK_OBJECT (ok_button5), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel5),
                      fileselection_5);
  gtk_signal_connect (GTK_OBJECT (cancel_button5), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel5),
                      fileselection_5);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_5), accel_group);

  return fileselection_5;
}

GtkWidget*
create_fileselection_6 (void)
{
  GtkWidget *fileselection_6;
  GtkWidget *ok_button6;
  GtkWidget *cancel_button6;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_6 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_6), "fileselection_6", fileselection_6);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_6), 10);

  ok_button6 = GTK_FILE_SELECTION (fileselection_6)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_6), "ok_button6", ok_button6);
  gtk_widget_show (ok_button6);
  GTK_WIDGET_SET_FLAGS (ok_button6, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button6, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button6 = GTK_FILE_SELECTION (fileselection_6)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_6), "cancel_button6", cancel_button6);
  gtk_widget_show (cancel_button6);
  GTK_WIDGET_SET_FLAGS (cancel_button6, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button6, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_6), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_6_show),
                      fileselection_6);
  gtk_signal_connect (GTK_OBJECT (ok_button6), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel6),
                      fileselection_6);
  gtk_signal_connect (GTK_OBJECT (cancel_button6), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel6),
                      fileselection_6);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_6), accel_group);

  return fileselection_6;
}

GtkWidget*
create_fileselection_7 (void)
{
  GtkWidget *fileselection_7;
  GtkWidget *ok_button7;
  GtkWidget *cancel_button7;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_7 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_7), "fileselection_7", fileselection_7);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_7), 10);

  ok_button7 = GTK_FILE_SELECTION (fileselection_7)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_7), "ok_button7", ok_button7);
  gtk_widget_show (ok_button7);
  GTK_WIDGET_SET_FLAGS (ok_button7, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button7, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button7 = GTK_FILE_SELECTION (fileselection_7)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_7), "cancel_button7", cancel_button7);
  gtk_widget_show (cancel_button7);
  GTK_WIDGET_SET_FLAGS (cancel_button7, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button7, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_7), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_7_show),
                      fileselection_7);
  gtk_signal_connect (GTK_OBJECT (ok_button7), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel7),
                      fileselection_7);
  gtk_signal_connect (GTK_OBJECT (cancel_button7), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel7),
                      fileselection_7);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_7), accel_group);

  return fileselection_7;
}

GtkWidget*
create_fileselection_8 (void)
{
  GtkWidget *fileselection_8;
  GtkWidget *ok_button8;
  GtkWidget *cancel_button8;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_8 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_8), "fileselection_8", fileselection_8);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_8), 10);

  ok_button8 = GTK_FILE_SELECTION (fileselection_8)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_8), "ok_button8", ok_button8);
  gtk_widget_show (ok_button8);
  GTK_WIDGET_SET_FLAGS (ok_button8, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button8, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button8 = GTK_FILE_SELECTION (fileselection_8)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_8), "cancel_button8", cancel_button8);
  gtk_widget_show (cancel_button8);
  GTK_WIDGET_SET_FLAGS (cancel_button8, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button8, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_8), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_8_show),
                      fileselection_8);
  gtk_signal_connect (GTK_OBJECT (ok_button8), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel8),
                      fileselection_8);
  gtk_signal_connect (GTK_OBJECT (cancel_button8), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel8),
                      fileselection_8);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_8), accel_group);

  return fileselection_8;
}

GtkWidget*
create_fileselection_9 (void)
{
  GtkWidget *fileselection_9;
  GtkWidget *ok_button9;
  GtkWidget *cancel_button9;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_9 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_9), "fileselection_9", fileselection_9);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_9), 10);

  ok_button9 = GTK_FILE_SELECTION (fileselection_9)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_9), "ok_button9", ok_button9);
  gtk_widget_show (ok_button9);
  GTK_WIDGET_SET_FLAGS (ok_button9, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button9, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button9 = GTK_FILE_SELECTION (fileselection_9)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_9), "cancel_button9", cancel_button9);
  gtk_widget_show (cancel_button9);
  GTK_WIDGET_SET_FLAGS (cancel_button9, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button9, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_9), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_9_show),
                      fileselection_9);
  gtk_signal_connect (GTK_OBJECT (ok_button9), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel9),
                      fileselection_9);
  gtk_signal_connect (GTK_OBJECT (cancel_button9), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel9),
                      fileselection_9);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_9), accel_group);

  return fileselection_9;
}

GtkWidget*
create_fileselection_10 (void)
{
  GtkWidget *fileselection_10;
  GtkWidget *ok_button10;
  GtkWidget *cancel_button10;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_10 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_10), "fileselection_10", fileselection_10);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_10), 10);

  ok_button10 = GTK_FILE_SELECTION (fileselection_10)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_10), "ok_button10", ok_button10);
  gtk_widget_show (ok_button10);
  GTK_WIDGET_SET_FLAGS (ok_button10, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button10, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button10 = GTK_FILE_SELECTION (fileselection_10)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_10), "cancel_button10", cancel_button10);
  gtk_widget_show (cancel_button10);
  GTK_WIDGET_SET_FLAGS (cancel_button10, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button10, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_10), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_10_show),
                      fileselection_10);
  gtk_signal_connect (GTK_OBJECT (ok_button10), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_fsel10),
                      fileselection_10);
  gtk_signal_connect (GTK_OBJECT (cancel_button10), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_fsel10),
                      fileselection_10);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_10), accel_group);

  return fileselection_10;
}

