/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_screendump_cb.h"
#include "gtk_screendump_dbox.h"
#include "support.h"

GtkWidget*
create_screendump_dbox (void)
{
  GtkWidget *screendump_dbox;
  GtkWidget *vbox1;
  GtkWidget *handlebox1;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *load1;
  GtkWidget *save1;
  GtkWidget *separator2;
  GtkWidget *quit1;
  GtkWidget *functions1;
  GtkWidget *functions1_menu;
  GtkAccelGroup *functions1_menu_accels;
  GtkWidget *recapture1;
  GtkWidget *options1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *help2;
  GtkWidget *about1;
  GtkWidget *handlebox2;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *frame2;
  GtkWidget *pixmap7;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  screendump_dbox = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (screendump_dbox), "screendump_dbox", screendump_dbox);
  gtk_window_set_title (GTK_WINDOW (screendump_dbox), _("Screen capture"));
  gtk_window_set_policy (GTK_WINDOW (screendump_dbox), TRUE, FALSE, FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (screendump_dbox), vbox1);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, FALSE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), menubar1);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  load1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (load1)->child),
                                   _("_Load"));
  gtk_widget_add_accelerator (load1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (load1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "load1", load1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load1);
  gtk_container_add (GTK_CONTAINER (file1_menu), load1);
  gtk_widget_add_accelerator (load1, "activate", accel_group,
                              GDK_L, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  save1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (save1)->child),
                                   _("_Save"));
  gtk_widget_add_accelerator (save1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (save1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "save1", save1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (file1_menu), save1);
  gtk_widget_add_accelerator (save1, "activate", accel_group,
                              GDK_S, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator2 = gtk_menu_item_new ();
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  quit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (quit1)->child),
                                   _("_Quit"));
  gtk_widget_add_accelerator (quit1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (quit1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "quit1", quit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), quit1);
  gtk_widget_add_accelerator (quit1, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  functions1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (functions1)->child),
                                   _("_Functions"));
  gtk_widget_add_accelerator (functions1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (functions1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "functions1", functions1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (functions1);
  gtk_container_add (GTK_CONTAINER (menubar1), functions1);

  functions1_menu = gtk_menu_new ();
  gtk_widget_ref (functions1_menu);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "functions1_menu", functions1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (functions1), functions1_menu);
  functions1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (functions1_menu));

  recapture1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (recapture1)->child),
                                   _("_Recapture"));
  gtk_widget_add_accelerator (recapture1, "activate_item", functions1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (recapture1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "recapture1", recapture1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (recapture1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), recapture1);
  gtk_widget_add_accelerator (recapture1, "activate", accel_group,
                              GDK_F1, 0,
                              GTK_ACCEL_VISIBLE);

  options1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (options1)->child),
                                   _("_Options"));
  gtk_widget_add_accelerator (options1, "activate_item", functions1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), options1);

  help1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help1)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help1));

  help1_menu = gtk_menu_new ();
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  help2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help2)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help2, "activate_item", help1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (help2);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "help2", help2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help2);
  gtk_container_add (GTK_CONTAINER (help1_menu), help2);
  gtk_widget_add_accelerator (help2, "activate", accel_group,
                              GDK_H, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  about1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about1)->child),
                                   _("_About"));
  gtk_widget_add_accelerator (about1, "activate_item", help1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox2);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "handlebox2", handlebox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar1);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar1), GTK_RELIEF_NONE);

  tmp_toolbar_icon = create_pixmap (screendump_dbox, "refresh.xpm");
  button1 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Refresh"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);

  tmp_toolbar_icon = create_pixmap (screendump_dbox, "floppy.xpm");
  button2 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Save"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);

  tmp_toolbar_icon = create_pixmap (screendump_dbox, "exit.xpm");
  button3 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Quit"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);

  tmp_toolbar_icon = create_pixmap (screendump_dbox, "help.xpm");
  button4 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Help"),
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);

  frame2 = gtk_frame_new (_("Calculator screen"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  pixmap7 = create_pixmap (screendump_dbox, "screendump.xpm");
  gtk_widget_ref (pixmap7);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "pixmap7", pixmap7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap7);
  gtk_container_add (GTK_CONTAINER (frame2), pixmap7);
  gtk_widget_set_usize (pixmap7, 240, 128);
  gtk_misc_set_padding (GTK_MISC (pixmap7), 2, 2);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (screendump_dbox), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (screendump_dbox), "show",
                      GTK_SIGNAL_FUNC (on_screendump_dbox_show1),
                      pixmap7);
  gtk_signal_connect (GTK_OBJECT (screendump_dbox), "show",
                      GTK_SIGNAL_FUNC (on_screendump_dbox_show2),
                      pixmap7);
  gtk_signal_connect (GTK_OBJECT (load1), "activate",
                      GTK_SIGNAL_FUNC (on_sc_load1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save1), "activate",
                      GTK_SIGNAL_FUNC (on_sc_save1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit1), "activate",
                      GTK_SIGNAL_FUNC (on_sc_quit1_activate),
                      screendump_dbox);
  gtk_signal_connect (GTK_OBJECT (recapture1), "activate",
                      GTK_SIGNAL_FUNC (on_sc_recapture1_activate),
                      pixmap7);
  gtk_signal_connect (GTK_OBJECT (options1), "activate",
                      GTK_SIGNAL_FUNC (on_sc_options1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (help2), "activate",
                      GTK_SIGNAL_FUNC (on_sc_help1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_sc_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_scdbox_button1_clicked),
                      pixmap7);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_scdbox_button2_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_scdbox_button3_clicked),
                      screendump_dbox);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_scdbox_button4_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (screendump_dbox), accel_group);

  return screendump_dbox;
}

GtkWidget*
create_screendump_fileselection (void)
{
  GtkWidget *screendump_fileselection;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  screendump_fileselection = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (screendump_fileselection), "screendump_fileselection", screendump_fileselection);
  gtk_container_set_border_width (GTK_CONTAINER (screendump_fileselection), 10);

  ok_button1 = GTK_FILE_SELECTION (screendump_fileselection)->ok_button;
  gtk_object_set_data (GTK_OBJECT (screendump_fileselection), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button1 = GTK_FILE_SELECTION (screendump_fileselection)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (screendump_fileselection), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (screendump_fileselection), "show",
                      GTK_SIGNAL_FUNC (on_screendump_fileselection_show),
                      screendump_fileselection);
  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_screendump_ok_button1_clicked),
                      screendump_fileselection);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_screendump_cancel_button1_clicked),
                      screendump_fileselection);

  gtk_window_add_accel_group (GTK_WINDOW (screendump_fileselection), accel_group);

  return screendump_fileselection;
}

GtkWidget*
create_screendump_fileselection2 (void)
{
  GtkWidget *screendump_fileselection2;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  screendump_fileselection2 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (screendump_fileselection2), "screendump_fileselection2", screendump_fileselection2);
  gtk_container_set_border_width (GTK_CONTAINER (screendump_fileselection2), 10);

  ok_button2 = GTK_FILE_SELECTION (screendump_fileselection2)->ok_button;
  gtk_object_set_data (GTK_OBJECT (screendump_fileselection2), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (screendump_fileselection2)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (screendump_fileselection2), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (screendump_fileselection2), "show",
                      GTK_SIGNAL_FUNC (on_screendump_fileselection2_show),
                      screendump_fileselection2);
  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_screendump_ok_button2_clicked),
                      screendump_fileselection2);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_screendump_cancel_button2_clicked),
                      screendump_fileselection2);

  gtk_window_add_accel_group (GTK_WINDOW (screendump_fileselection2), accel_group);

  return screendump_fileselection2;
}

