/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fileselection_1 (void);
GtkWidget* create_fileselection_2 (void);
GtkWidget* create_fileselection_3 (void);
GtkWidget* create_fileselection_4 (void);
GtkWidget* create_fileselection_5 (void);
GtkWidget* create_fileselection_6 (void);
GtkWidget* create_fileselection_7 (void);
GtkWidget* create_fileselection_8 (void);
GtkWidget* create_fileselection_9 (void);
GtkWidget* create_fileselection_10 (void);
