/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_term_cb.h"
#include "gtk_term_dbox.h"
#include "support.h"

GtkWidget*
create_term_dbox (void)
{
  GtkWidget *term_dbox;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *quit1;
  GtkWidget *mode1;
  GtkWidget *mode1_menu;
  GtkAccelGroup *mode1_menu_accels;
  GtkWidget *remote_control1;
  GtkWidget *terminal1;
  GtkWidget *leave1;
  GtkWidget *help2;
  GtkWidget *help2_menu;
  GtkAccelGroup *help2_menu_accels;
  GtkWidget *help3;
  GtkWidget *manpage1;
  GtkWidget *separator2;
  GtkWidget *about1;
  GtkWidget *scrolledwindow1;
  GtkWidget *text1;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  term_dbox = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (term_dbox), "term_dbox", term_dbox);
  gtk_widget_set_usize (term_dbox, 320, 240);
  gtk_window_set_title (GTK_WINDOW (term_dbox), _("Remote control/terminal"));
  gtk_window_set_policy (GTK_WINDOW (term_dbox), TRUE, TRUE, FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (term_dbox), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  quit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (quit1)->child),
                                   _("_Quit"));
  gtk_widget_add_accelerator (quit1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (quit1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "quit1", quit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menubar1), quit1);

  mode1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (mode1)->child),
                                   _("_Mode"));
  gtk_widget_add_accelerator (mode1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (mode1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "mode1", mode1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mode1);
  gtk_container_add (GTK_CONTAINER (menubar1), mode1);

  mode1_menu = gtk_menu_new ();
  gtk_widget_ref (mode1_menu);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "mode1_menu", mode1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (mode1), mode1_menu);
  mode1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (mode1_menu));

  remote_control1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (remote_control1)->child),
                                   _("_Remote control"));
  gtk_widget_add_accelerator (remote_control1, "activate_item", mode1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (remote_control1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "remote_control1", remote_control1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (remote_control1);
  gtk_container_add (GTK_CONTAINER (mode1_menu), remote_control1);

  terminal1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (terminal1)->child),
                                   _("_Terminal"));
  gtk_widget_add_accelerator (terminal1, "activate_item", mode1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (terminal1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "terminal1", terminal1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (terminal1);
  gtk_container_add (GTK_CONTAINER (mode1_menu), terminal1);

  leave1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (leave1)->child),
                                   _("_Leave"));
  gtk_widget_add_accelerator (leave1, "activate_item", mode1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (leave1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "leave1", leave1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (leave1);
  gtk_container_add (GTK_CONTAINER (mode1_menu), leave1);

  help2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help2)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help2, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (help2);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "help2", help2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help2);
  gtk_container_add (GTK_CONTAINER (menubar1), help2);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help2));

  help2_menu = gtk_menu_new ();
  gtk_widget_ref (help2_menu);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "help2_menu", help2_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help2), help2_menu);
  help2_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help2_menu));

  help3 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help3)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help3, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (help3);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "help3", help3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help3);
  gtk_container_add (GTK_CONTAINER (help2_menu), help3);

  manpage1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (manpage1)->child),
                                   _("_Manpage"));
  gtk_widget_add_accelerator (manpage1, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (manpage1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "manpage1", manpage1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage1);
  gtk_container_add (GTK_CONTAINER (help2_menu), manpage1);

  separator2 = gtk_menu_item_new ();
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (help2_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  about1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about1)->child),
                                   _("_About"));
  gtk_widget_add_accelerator (about1, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help2_menu), about1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  text1 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "text1", text1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), text1);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (term_dbox), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (term_dbox), "show",
                      GTK_SIGNAL_FUNC (on_term_dbox_show_text),
                      text1);
  gtk_signal_connect (GTK_OBJECT (term_dbox), "show",
                      GTK_SIGNAL_FUNC (on_term_dbox_show_dbox),
                      term_dbox);
  gtk_signal_connect (GTK_OBJECT (quit1), "activate",
                      GTK_SIGNAL_FUNC (on_term_quit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (remote_control1), "activate",
                      GTK_SIGNAL_FUNC (on_term_remote_control1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (terminal1), "activate",
                      GTK_SIGNAL_FUNC (on_term_terminal1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (leave1), "activate",
                      GTK_SIGNAL_FUNC (on_term_leave1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (help3), "activate",
                      GTK_SIGNAL_FUNC (on_term_help3_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpage1), "activate",
                      GTK_SIGNAL_FUNC (on_term_manpage1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_term_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (text1), "key_press_event",
                      GTK_SIGNAL_FUNC (on_text1_key_press_event),
                      text1);

  gtk_window_add_accel_group (GTK_WINDOW (term_dbox), accel_group);

  return term_dbox;
}

