language: c

addons:
  apt:
    packages:
      - build-essential
      - git
      - autoconf
      - automake
      - autopoint
      - libtool
      - libglib2.0-dev
      - libgtk2.0-dev
      - libgtk-3-dev
      - libglade2-dev
      - zlib1g-dev
      - libusb-1.0-0-dev
      - gettext
      - bison
      - flex
      - groff
      - texinfo
      - intltool
      - libarchive-dev
      - cmake
      - ninja-build
      - liblz4-dev
      - liblzma-dev

matrix:
  include:
    - os: linux
      dist: xenial
      arch: amd64
      sudo: required
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=OFF"
    - os: linux
      dist: bionic
      arch: amd64
      sudo: required
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=OFF"
    - os: linux
      dist: bionic
      arch: arm64
      sudo: required
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=OFF"
    - os: linux
      dist: xenial
      arch: amd64
      sudo: required
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=ON"
    - os: linux
      dist: bionic
      arch: amd64
      sudo: required
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=ON"
    - os: linux
      dist: bionic
      arch: arm64
      sudo: required
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=ON"
    - os: osx
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=OFF"
    - os: osx
      env: GTK3OPTION="-DBUILD_USING_GTK3:BOOL=ON"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake ninja gettext gtk+ gtk+3 libglade libarchive libtool glib libusb bison flex texinfo libiconv intltool ; brew link --force gettext libarchive ; export PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig"; fi
  - which gcc   ; gcc --version
  - which cmake ; cmake --version
  - which ninja ; ninja --version
  - which make  ; make --version

# We do not need sudo to install to the default prefix on macOS (/usr/local/), but on Linux we do.
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DOSUDO=sudo && export setprefix="-DCMAKE_INSTALL_PREFIX=/usr"; fi
  - git clone --depth 1 https://github.com/debrouxl/tilibs.git
  - cd tilibs
  - mkdir build && cd build
  - cmake -GNinja .. ${setprefix}
  - $DOSUDO cmake --build . --target install
  - cd ..
  - cd ..
  - cd  gfm/trunk/po; intltool-update --pot; intltool-update fr; cd ../../..
  - cd tilp/trunk/po; intltool-update --pot; intltool-update fr; intltool-update de; cd ../../..
  - mkdir build && cd build
  - cmake -GNinja .. ${setprefix} ${GTK3OPTION}
  - $DOSUDO cmake --build . --target install
  - tilp2 --version
  - gfm --version
