/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_extprgms_cb.h"
#include "gtk_extprgms_dbox.h"
#include "support.h"

GtkWidget*
create_extprgms_dbox (void)
{
  GtkWidget *extprgms_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *vbox2;
  GtkWidget *label1;
  GtkWidget *hbox1;
  GtkWidget *entry1;
  GtkWidget *button3;
  GtkWidget *label3;
  GtkWidget *entry3;
  GtkWidget *frame2;
  GtkWidget *vbox3;
  GtkWidget *label2;
  GtkWidget *hbox2;
  GtkWidget *entry2;
  GtkWidget *button4;
  GtkWidget *label4;
  GtkWidget *entry4;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *hbox4;
  GtkWidget *pixmap2;
  guint label6_key;
  GtkWidget *label6;
  GtkWidget *button2;
  GtkWidget *hbox3;
  GtkWidget *pixmap1;
  guint label5_key;
  GtkWidget *label5;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  extprgms_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (extprgms_dbox), "extprgms_dbox", extprgms_dbox);
  gtk_window_set_title (GTK_WINDOW (extprgms_dbox), _("External programs location"));
  gtk_window_set_policy (GTK_WINDOW (extprgms_dbox), FALSE, FALSE, FALSE);

  dialog_vbox1 = GTK_DIALOG (extprgms_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (extprgms_dbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (_("ZIP program:"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  vbox2 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame1), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 2);

  label1 = gtk_label_new (_("Location:"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox2), label1, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox1), entry1, TRUE, TRUE, 5);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("wzunzip.exe"));

  button3 = gtk_button_new_with_label (_("..."));
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (hbox1), button3, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Options:"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox2), label3, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_ref (entry3);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "entry3", entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (vbox2), entry3, FALSE, FALSE, 0);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("-d"));

  frame2 = gtk_frame_new (_("TAR.GZ/TGZ program:"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  vbox3 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame2), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 2);

  label2 = gtk_label_new (_("Location:"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox3), label2, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox2, TRUE, TRUE, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_ref (entry2);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "entry2", entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry2);
  gtk_box_pack_start (GTK_BOX (hbox2), entry2, TRUE, TRUE, 5);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("tar"));

  button4 = gtk_button_new_with_label (_("..."));
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (hbox2), button4, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("Options:\t"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox3), label4, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 5, 0);

  entry4 = gtk_entry_new ();
  gtk_widget_ref (entry4);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "entry4", entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry4);
  gtk_box_pack_start (GTK_BOX (vbox3), entry4, FALSE, FALSE, 0);
  gtk_entry_set_text (GTK_ENTRY (entry4), _("xvzf"));

  dialog_action_area1 = GTK_DIALOG (extprgms_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (extprgms_dbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  button1 = gtk_button_new ();
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (button1), hbox4);

  pixmap2 = create_pixmap (extprgms_dbox, "yes.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox4), pixmap2, TRUE, FALSE, 0);

  label6 = gtk_label_new ("");
  label6_key = gtk_label_parse_uline (GTK_LABEL (label6),
                                   _("_OK"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  button2 = gtk_button_new ();
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (button2), hbox3);

  pixmap1 = create_pixmap (extprgms_dbox, "no.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox3), pixmap1, TRUE, FALSE, 0);

  label5 = gtk_label_new ("");
  label5_key = gtk_label_parse_uline (GTK_LABEL (label5),
                                   _("_Cancel"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (extprgms_dbox), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  gtk_signal_connect (GTK_OBJECT (extprgms_dbox), "show",
                      GTK_SIGNAL_FUNC (on_extprgms_dbox_show),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (extprgms_dbox), "show",
                      GTK_SIGNAL_FUNC (on_extprgms_dbox_show1),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (extprgms_dbox), "show",
                      GTK_SIGNAL_FUNC (on_extprgms_dbox_show3),
                      entry3);
  gtk_signal_connect (GTK_OBJECT (extprgms_dbox), "show",
                      GTK_SIGNAL_FUNC (on_extprgms_dbox_show2),
                      entry2);
  gtk_signal_connect (GTK_OBJECT (extprgms_dbox), "show",
                      GTK_SIGNAL_FUNC (on_extprgms_dbox_show4),
                      entry4);
  gtk_signal_connect (GTK_OBJECT (entry1), "changed",
                      GTK_SIGNAL_FUNC (on_entry1_changed),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_button3_clicked),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (entry3), "changed",
                      GTK_SIGNAL_FUNC (on_entry3_changed),
                      entry3);
  gtk_signal_connect (GTK_OBJECT (entry2), "changed",
                      GTK_SIGNAL_FUNC (on_entry2_changed),
                      entry2);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_button4_clicked),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (entry4), "changed",
                      GTK_SIGNAL_FUNC (on_entry4_changed),
                      entry4);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_button1_clicked),
                      extprgms_dbox);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_button2_clicked),
                      extprgms_dbox);

  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              label6_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (button2, "clicked", accel_group,
                              label5_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (extprgms_dbox), accel_group);

  return extprgms_dbox;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection1 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection1), "fileselection1", fileselection1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_modal (GTK_WINDOW (fileselection1), TRUE);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button1_clicked),
                      fileselection1);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button1_clicked),
                      fileselection1);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection1), accel_group);

  return fileselection1;
}

GtkWidget*
create_fileselection2 (void)
{
  GtkWidget *fileselection2;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection2 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection2), "fileselection2", fileselection2);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection2), 10);

  ok_button2 = GTK_FILE_SELECTION (fileselection2)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection2), "ok_button2", ok_button2);
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button2 = GTK_FILE_SELECTION (fileselection2)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection2), "cancel_button2", cancel_button2);
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (ok_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button2_clicked),
                      fileselection2);
  gtk_signal_connect (GTK_OBJECT (cancel_button2), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button2_clicked),
                      fileselection2);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection2), accel_group);

  return fileselection2;
}

