/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_clist_cb.h"
#include "gtk_clist_rbm.h"
#include "support.h"

GtkWidget*
create_clist_rbm (void)
{
  GtkWidget *clist_rbm;
  GtkAccelGroup *clist_rbm_accels;
  guint tmp_key;
  GtkWidget *edit1;
  GtkWidget *edit1_menu;
  GtkAccelGroup *edit1_menu_accels;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *separator1;
  GtkWidget *move_to_parent_dir1;
  GtkWidget *select_all1;
  GtkWidget *unselect_all1;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *unzip1;
  GtkWidget *untar1;
  GtkWidget *ungroup1;
  GtkWidget *unpack1;
  GtkWidget *view1;
  GtkWidget *separator2;
  GtkWidget *rename1;
  GtkWidget *properties1;
  GtkWidget *update_window1;
  GtkWidget *make_a_new_dir1;
  GtkWidget *delete_file1;
  GtkWidget *calc1;
  GtkWidget *calc1_menu;
  GtkAccelGroup *calc1_menu_accels;
  GtkWidget *insert_shell1;
  GtkWidget *insert_shell1_menu;
  GtkAccelGroup *insert_shell1_menu_accels;
  GtkWidget *fargo_ii1;
  GtkWidget *plugins1;
  GtkWidget *shell1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  clist_rbm = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (clist_rbm), "clist_rbm", clist_rbm);
  clist_rbm_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (clist_rbm));

  edit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (edit1)->child),
                                   _("_Edit"));
  gtk_widget_add_accelerator (edit1, "activate_item", clist_rbm_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (edit1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "edit1", edit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit1);
  gtk_container_add (GTK_CONTAINER (clist_rbm), edit1);

  edit1_menu = gtk_menu_new ();
  gtk_widget_ref (edit1_menu);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "edit1_menu", edit1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit1), edit1_menu);
  edit1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (edit1_menu));

  cut1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (cut1)->child),
                                   _("_Cut"));
  gtk_widget_add_accelerator (cut1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (cut1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "cut1", cut1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), cut1);
  gtk_tooltips_set_tip (tooltips, cut1, _("Cut selected files"), NULL);

  copy1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (copy1)->child),
                                   _("C_opy"));
  gtk_widget_add_accelerator (copy1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (copy1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "copy1", copy1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), copy1);
  gtk_tooltips_set_tip (tooltips, copy1, _("Copy selected files"), NULL);

  paste1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (paste1)->child),
                                   _("_Paste"));
  gtk_widget_add_accelerator (paste1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (paste1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "paste1", paste1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), paste1);
  gtk_tooltips_set_tip (tooltips, paste1, _("Paste previously selected files"), NULL);

  separator1 = gtk_menu_item_new ();
  gtk_widget_ref (separator1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "separator1", separator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  move_to_parent_dir1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (move_to_parent_dir1)->child),
                                   _("_Move to parent dir"));
  gtk_widget_add_accelerator (move_to_parent_dir1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (move_to_parent_dir1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "move_to_parent_dir1", move_to_parent_dir1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (move_to_parent_dir1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), move_to_parent_dir1);
  gtk_tooltips_set_tip (tooltips, move_to_parent_dir1, _("Change to the parent directory"), NULL);

  select_all1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (select_all1)->child),
                                   _("_Select all"));
  gtk_widget_add_accelerator (select_all1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (select_all1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "select_all1", select_all1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (select_all1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), select_all1);
  gtk_tooltips_set_tip (tooltips, select_all1, _("Select all files"), NULL);

  unselect_all1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (unselect_all1)->child),
                                   _("_Unselect all"));
  gtk_widget_add_accelerator (unselect_all1, "activate_item", edit1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (unselect_all1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "unselect_all1", unselect_all1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unselect_all1);
  gtk_container_add (GTK_CONTAINER (edit1_menu), unselect_all1);
  gtk_tooltips_set_tip (tooltips, unselect_all1, _("Unselect all files"), NULL);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file1, "activate_item", clist_rbm_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (clist_rbm), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  unzip1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (unzip1)->child),
                                   _("Un_zip"));
  gtk_widget_add_accelerator (unzip1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (unzip1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "unzip1", unzip1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unzip1);
  gtk_container_add (GTK_CONTAINER (file1_menu), unzip1);
  gtk_tooltips_set_tip (tooltips, unzip1, _("Unzip selected file(s)"), NULL);

  untar1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (untar1)->child),
                                   _("Un_tar"));
  gtk_widget_add_accelerator (untar1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (untar1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "untar1", untar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (untar1);
  gtk_container_add (GTK_CONTAINER (file1_menu), untar1);
  gtk_tooltips_set_tip (tooltips, untar1, _("Untar (tar.gz/tgz) selected file(s)"), NULL);

  ungroup1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (ungroup1)->child),
                                   _("Un_group"));
  gtk_widget_add_accelerator (ungroup1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (ungroup1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "ungroup1", ungroup1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ungroup1);
  gtk_container_add (GTK_CONTAINER (file1_menu), ungroup1);
  gtk_tooltips_set_tip (tooltips, ungroup1, _("Ungroup selected file(s)"), NULL);

  unpack1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (unpack1)->child),
                                   _("Un_pack"));
  gtk_widget_add_accelerator (unpack1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (unpack1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "unpack1", unpack1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unpack1);
  gtk_container_add (GTK_CONTAINER (file1_menu), unpack1);
  gtk_tooltips_set_tip (tooltips, unpack1, _("Unpack selected file(s)"), NULL);

  view1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (view1)->child),
                                   _("_View"));
  gtk_widget_add_accelerator (view1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (view1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "view1", view1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (view1);
  gtk_container_add (GTK_CONTAINER (file1_menu), view1);
  gtk_tooltips_set_tip (tooltips, view1, _("View selected file(s)"), NULL);

  separator2 = gtk_menu_item_new ();
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  rename1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (rename1)->child),
                                   _("_Rename"));
  gtk_widget_add_accelerator (rename1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (rename1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "rename1", rename1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rename1);
  gtk_container_add (GTK_CONTAINER (file1_menu), rename1);
  gtk_tooltips_set_tip (tooltips, rename1, _("Rename file(s)"), NULL);

  properties1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (properties1)->child),
                                   _("_Properties"));
  gtk_widget_add_accelerator (properties1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (properties1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "properties1", properties1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (properties1);
  gtk_container_add (GTK_CONTAINER (file1_menu), properties1);
  gtk_tooltips_set_tip (tooltips, properties1, _("Display some informations about the file"), NULL);

  update_window1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (update_window1)->child),
                                   _("_Update window"));
  gtk_widget_add_accelerator (update_window1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (update_window1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "update_window1", update_window1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (update_window1);
  gtk_container_add (GTK_CONTAINER (file1_menu), update_window1);
  gtk_tooltips_set_tip (tooltips, update_window1, _("Refresh file informations"), NULL);

  make_a_new_dir1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (make_a_new_dir1)->child),
                                   _("Make a new _dir"));
  gtk_widget_add_accelerator (make_a_new_dir1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (make_a_new_dir1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "make_a_new_dir1", make_a_new_dir1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (make_a_new_dir1);
  gtk_container_add (GTK_CONTAINER (file1_menu), make_a_new_dir1);
  gtk_tooltips_set_tip (tooltips, make_a_new_dir1, _("Make a new directory"), NULL);

  delete_file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (delete_file1)->child),
                                   _("_Delete file"));
  gtk_widget_add_accelerator (delete_file1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (delete_file1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "delete_file1", delete_file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete_file1);
  gtk_container_add (GTK_CONTAINER (file1_menu), delete_file1);
  gtk_tooltips_set_tip (tooltips, delete_file1, _("Delete selected file(s)"), NULL);

  calc1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (calc1)->child),
                                   _("_Calc"));
  gtk_widget_add_accelerator (calc1, "activate_item", clist_rbm_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (calc1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "calc1", calc1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (calc1);
  gtk_container_add (GTK_CONTAINER (clist_rbm), calc1);

  calc1_menu = gtk_menu_new ();
  gtk_widget_ref (calc1_menu);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "calc1_menu", calc1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (calc1), calc1_menu);
  calc1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (calc1_menu));

  insert_shell1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (insert_shell1)->child),
                                   _("_Insert shell"));
  gtk_widget_add_accelerator (insert_shell1, "activate_item", calc1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (insert_shell1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "insert_shell1", insert_shell1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (insert_shell1);
  gtk_container_add (GTK_CONTAINER (calc1_menu), insert_shell1);

  insert_shell1_menu = gtk_menu_new ();
  gtk_widget_ref (insert_shell1_menu);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "insert_shell1_menu", insert_shell1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (insert_shell1), insert_shell1_menu);
  insert_shell1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (insert_shell1_menu));

  fargo_ii1 = gtk_menu_item_new_with_label (_("FARGO II"));
  gtk_widget_ref (fargo_ii1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "fargo_ii1", fargo_ii1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (fargo_ii1);
  gtk_container_add (GTK_CONTAINER (insert_shell1_menu), fargo_ii1);

  plugins1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (plugins1)->child),
                                   _("_Plugins"));
  gtk_widget_add_accelerator (plugins1, "activate_item", clist_rbm_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (plugins1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "plugins1", plugins1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (plugins1);
  gtk_container_add (GTK_CONTAINER (clist_rbm), plugins1);

  shell1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (shell1)->child),
                                   _("_Console"));
  gtk_widget_add_accelerator (shell1, "activate_item", clist_rbm_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (shell1);
  gtk_object_set_data_full (GTK_OBJECT (clist_rbm), "shell1", shell1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (shell1);
  gtk_container_add (GTK_CONTAINER (clist_rbm), shell1);

  gtk_signal_connect (GTK_OBJECT (clist_rbm), "show",
                      GTK_SIGNAL_FUNC (on_clist_rbm_show),
                      clist_rbm);
  gtk_signal_connect (GTK_OBJECT (cut1), "activate",
                      GTK_SIGNAL_FUNC (on_cut1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (copy1), "activate",
                      GTK_SIGNAL_FUNC (on_copy1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (paste1), "activate",
                      GTK_SIGNAL_FUNC (on_paste1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (move_to_parent_dir1), "activate",
                      GTK_SIGNAL_FUNC (on_move_to_parent_dir1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (select_all1), "activate",
                      GTK_SIGNAL_FUNC (on_select_all1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unselect_all1), "activate",
                      GTK_SIGNAL_FUNC (on_unselect_all1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unzip1), "activate",
                      GTK_SIGNAL_FUNC (on_unzip1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (untar1), "activate",
                      GTK_SIGNAL_FUNC (on_untar1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ungroup1), "activate",
                      GTK_SIGNAL_FUNC (on_ungroup1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unpack1), "activate",
                      GTK_SIGNAL_FUNC (on_unpack1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (view1), "activate",
                      GTK_SIGNAL_FUNC (on_view1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rename1), "activate",
                      GTK_SIGNAL_FUNC (on_rename1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (properties1), "activate",
                      GTK_SIGNAL_FUNC (on_properties1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (update_window1), "activate",
                      GTK_SIGNAL_FUNC (on_update_window1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (make_a_new_dir1), "activate",
                      GTK_SIGNAL_FUNC (on_make_a_new_dir1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (delete_file1), "activate",
                      GTK_SIGNAL_FUNC (on_delete_file1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (fargo_ii1), "activate",
                      GTK_SIGNAL_FUNC (on_fargo_ii1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (plugins1), "activate",
                      GTK_SIGNAL_FUNC (on_plugins1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (shell1), "activate",
                      GTK_SIGNAL_FUNC (on_shell1_activate),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (clist_rbm), "tooltips", tooltips);

  return clist_rbm;
}

