/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_link_cb.h"
#include "gtk_link_dbox.h"
#include "support.h"

GtkWidget*
create_linktype_dbox (void)
{
  GtkWidget *linktype_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *frame4;
  GtkWidget *table3;
  GtkWidget *button1;
  GtkWidget *label2;
  GtkWidget *label8;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *frame3;
  GtkWidget *hbox1;
  GtkWidget *checkbutton1;
  GtkWidget *label1;
  GtkWidget *checkbutton2;
  GtkWidget *label5;
  GtkWidget *checkbutton3;
  GtkWidget *label9;
  GtkWidget *frame1;
  GtkWidget *table2;
  GSList *link_group_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *label4;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton1;
  GtkWidget *label3;
  GtkWidget *frame2;
  GtkWidget *vbox2;
  GSList *port_group_group = NULL;
  GtkWidget *radiobutton10;
  GtkWidget *radiobutton11;
  GtkWidget *radiobutton12;
  GtkWidget *radiobutton13;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *ok_button;
  GtkWidget *hbox3;
  GtkWidget *pixmap2;
  guint label7_key;
  GtkWidget *label7;
  GtkWidget *cancel_button;
  GtkWidget *hbox2;
  GtkWidget *pixmap1;
  guint label6_key;
  GtkWidget *label6;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  linktype_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (linktype_dbox), "linktype_dbox", linktype_dbox);
  gtk_window_set_title (GTK_WINDOW (linktype_dbox), _("Configuration of the link cable and I/O ports"));
  gtk_window_set_policy (GTK_WINDOW (linktype_dbox), FALSE, FALSE, TRUE);

  dialog_vbox1 = GTK_DIALOG (linktype_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (linktype_dbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, FALSE, TRUE, 0);

  frame4 = gtk_frame_new (_("Specify I/O or device:"));
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_table_attach (GTK_TABLE (table1), frame4, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);

  table3 = gtk_table_new (2, 3, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame4), table3);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  button1 = gtk_button_new_with_label (_("..."));
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_table_attach (GTK_TABLE (table3), button1, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label2 = gtk_label_new (_("I/O address:"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table3), label2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  label8 = gtk_label_new (_("I/O device:"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table3), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 5, 0);

  entry1 = gtk_entry_new_with_max_length (5);
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table3), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry1, 50, -2);
  gtk_entry_set_text (GTK_ENTRY (entry1), _("*****"));

  entry2 = gtk_entry_new_with_max_length (255);
  gtk_widget_ref (entry2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "entry2", entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table3), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (entry2, 55, -2);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("/dev/"));

  frame3 = gtk_frame_new (_("Options:"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_table_attach (GTK_TABLE (table1), frame3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 5);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (frame3), hbox1);

  checkbutton1 = gtk_check_button_new ();
  gtk_widget_ref (checkbutton1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "checkbutton1", checkbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (hbox1), checkbutton1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton1), 5);

  label1 = gtk_label_new (_("Kernel \ndriver"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_container_add (GTK_CONTAINER (checkbutton1), label1);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label1), 0.05, 0.5);

  checkbutton2 = gtk_check_button_new ();
  gtk_widget_ref (checkbutton2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "checkbutton2", checkbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton2);
  gtk_box_pack_start (GTK_BOX (hbox1), checkbutton2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton2), 5);

  label5 = gtk_label_new (_("DCB (Win32)"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_container_add (GTK_CONTAINER (checkbutton2), label5);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 0.05, 0.5);

  checkbutton3 = gtk_check_button_new ();
  gtk_widget_ref (checkbutton3);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "checkbutton3", checkbutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton3);
  gtk_box_pack_start (GTK_BOX (hbox1), checkbutton3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton3), 5);

  label9 = gtk_label_new (_("custom\nsettings"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (checkbutton3), label9);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label9), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label9), 0.05, 0.5);

  frame1 = gtk_frame_new (_("Link cable type:"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_table_attach (GTK_TABLE (table1), frame1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  table2 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (frame1), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 5);

  radiobutton3 = gtk_radio_button_new_with_label (link_group_group, _("TIEmulator virtual link"));
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton3));
  gtk_widget_ref (radiobutton3);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton3", radiobutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton3);
  gtk_table_attach (GTK_TABLE (table2), radiobutton3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton2 = gtk_radio_button_new_with_label (link_group_group, _("Home-made parallel"));
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton2));
  gtk_widget_ref (radiobutton2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton2", radiobutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton2);
  gtk_table_attach (GTK_TABLE (table2), radiobutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton4 = gtk_radio_button_new_with_label (link_group_group, _("TI/PC USB link"));
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton4));
  gtk_widget_ref (radiobutton4);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton4", radiobutton4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton4);
  gtk_table_attach (GTK_TABLE (table2), radiobutton4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton5 = gtk_radio_button_new (link_group_group);
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton5));
  gtk_widget_ref (radiobutton5);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton5", radiobutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton5);
  gtk_table_attach (GTK_TABLE (table2), radiobutton5, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label4 = gtk_label_new (_("Black TIGraphLink\nHome-made serial"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (radiobutton5), label4);

  radiobutton6 = gtk_radio_button_new_with_label (link_group_group, _("fastAVRlink"));
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton6));
  gtk_widget_ref (radiobutton6);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton6", radiobutton6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton6);
  gtk_table_attach (GTK_TABLE (table2), radiobutton6, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton7 = gtk_radio_button_new_with_label (link_group_group, _("VTi virtual link"));
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton7));
  gtk_widget_ref (radiobutton7);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton7", radiobutton7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton7);
  gtk_table_attach (GTK_TABLE (table2), radiobutton7, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton8 = gtk_radio_button_new_with_label (link_group_group, _("TIGraphLink USB"));
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton8));
  gtk_widget_ref (radiobutton8);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton8", radiobutton8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton8);
  gtk_table_attach (GTK_TABLE (table2), radiobutton8, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton1 = gtk_radio_button_new (link_group_group);
  link_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton1));
  gtk_widget_ref (radiobutton1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton1", radiobutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton1);
  gtk_table_attach (GTK_TABLE (table2), radiobutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton1), TRUE);

  label3 = gtk_label_new (_("Grey TIGraphLink\nAVRlink"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (radiobutton1), label3);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  frame2 = gtk_frame_new (_("I/O port:"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_table_attach (GTK_TABLE (table1), frame2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame2), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  radiobutton10 = gtk_radio_button_new_with_label (port_group_group, _("0x3f8 (COM1)"));
  port_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton10));
  gtk_widget_ref (radiobutton10);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton10", radiobutton10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton10);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton10, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton10), TRUE);

  radiobutton11 = gtk_radio_button_new_with_label (port_group_group, _("0x2f8 (COM2)"));
  port_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton11));
  gtk_widget_ref (radiobutton11);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton11", radiobutton11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton11);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton11, FALSE, FALSE, 0);

  radiobutton12 = gtk_radio_button_new_with_label (port_group_group, _("0x3e8 (COM3)"));
  port_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton12));
  gtk_widget_ref (radiobutton12);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton12", radiobutton12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton12);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton12, FALSE, FALSE, 0);

  radiobutton13 = gtk_radio_button_new_with_label (port_group_group, _("0x2e8 (COM4)"));
  port_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton13));
  gtk_widget_ref (radiobutton13);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "radiobutton13", radiobutton13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton13);
  gtk_box_pack_start (GTK_BOX (vbox2), radiobutton13, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (linktype_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (linktype_dbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  ok_button = gtk_button_new ();
  gtk_widget_ref (ok_button);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "ok_button", ok_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (ok_button), hbox3);

  pixmap2 = create_pixmap (linktype_dbox, "yes.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox3), pixmap2, TRUE, FALSE, 0);

  label7 = gtk_label_new ("");
  label7_key = gtk_label_parse_uline (GTK_LABEL (label7),
                                   _("_OK"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 5, 0);

  cancel_button = gtk_button_new ();
  gtk_widget_ref (cancel_button);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "cancel_button", cancel_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (cancel_button), hbox2);

  pixmap1 = create_pixmap (linktype_dbox, "no.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap1, TRUE, FALSE, 0);

  label6 = gtk_label_new ("");
  label6_key = gtk_label_parse_uline (GTK_LABEL (label6),
                                   _("_Cancel"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (linktype_dbox), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show30),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show31),
                      entry2);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show1),
                      radiobutton1);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show2),
                      radiobutton2);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show3),
                      radiobutton3);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show4),
                      radiobutton4);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show5),
                      radiobutton5);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show6),
                      radiobutton6);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show7),
                      radiobutton7);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show8),
                      radiobutton8);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show10),
                      checkbutton1);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show11),
                      checkbutton2);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show20),
                      radiobutton10);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show21),
                      radiobutton11);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show22),
                      radiobutton12);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show23),
                      radiobutton13);
  gtk_signal_connect (GTK_OBJECT (linktype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_linktype_dbox_show40),
                      label1);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_linktype_button_fs_clicked),
                      entry2);
  gtk_signal_connect (GTK_OBJECT (entry1), "changed",
                      GTK_SIGNAL_FUNC (linktype_entry1_changed),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (entry2), "changed",
                      GTK_SIGNAL_FUNC (linktype_entry2_changed),
                      entry2);
  gtk_signal_connect (GTK_OBJECT (checkbutton1), "toggled",
                      GTK_SIGNAL_FUNC (linktype_checkbutton1_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (checkbutton2), "toggled",
                      GTK_SIGNAL_FUNC (linktype_checkbutton2_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (checkbutton3), "toggled",
                      GTK_SIGNAL_FUNC (linktype_checkbutton3_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton3), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton3_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton2), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton2_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton4), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton4_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton5), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton5_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton6), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton6_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton7), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton7_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton8), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton8_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton1), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton1_toggled),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (radiobutton10), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton10_toggled),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (radiobutton11), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton11_toggled),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (radiobutton12), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton12_toggled),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (radiobutton13), "toggled",
                      GTK_SIGNAL_FUNC (linktype_radiobutton13_toggled),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (ok_button), "clicked",
                      GTK_SIGNAL_FUNC (linktype_ok_button_clicked),
                      linktype_dbox);
  gtk_signal_connect (GTK_OBJECT (cancel_button), "clicked",
                      GTK_SIGNAL_FUNC (linktype_cancel_button_clicked),
                      linktype_dbox);

  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              label7_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              label6_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);

  gtk_window_add_accel_group (GTK_WINDOW (linktype_dbox), accel_group);

  return linktype_dbox;
}

GtkWidget*
create_fileselection_device (void)
{
  GtkWidget *fileselection_device;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  fileselection_device = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection_device), "fileselection_device", fileselection_device);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection_device), 10);

  ok_button1 = GTK_FILE_SELECTION (fileselection_device)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_device), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  cancel_button1 = GTK_FILE_SELECTION (fileselection_device)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection_device), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (fileselection_device), "show",
                      GTK_SIGNAL_FUNC (on_fileselection_device_show),
                      fileselection_device);
  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_seldev_ok_button1_clicked),
                      fileselection_device);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_seldev_cancel_button1_clicked),
                      fileselection_device);

  gtk_window_add_accel_group (GTK_WINDOW (fileselection_device), accel_group);

  return fileselection_device;
}

