/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_screendump_dbox (void);
GtkWidget* create_screendump_fileselection (void);
GtkWidget* create_screendump_fileselection2 (void);
