/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_tilp_cb.h"
#include "gtk_tilp_dbox.h"
#include "support.h"

GtkWidget*
create_tilp_dbox (void)
{
  GtkWidget *tilp_dbox;
  GtkWidget *vbox1;
  GtkWidget *handlebox1;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *convert_old_files1;
  GtkWidget *convert_flash_to_rom1;
  GtkWidget *separator73;
  GtkWidget *unzip_archive1;
  GtkWidget *untar_archive1;
  GtkWidget *separator74;
  GtkWidget *unpack__obsolete_1;
  GtkWidget *group_file_manager1;
  GtkWidget *separator12;
  GtkWidget *save_config1;
  GtkWidget *reload_config1;
  GtkWidget *default_config1;
  GtkWidget *separator13;
  GtkWidget *quit1;
  GtkWidget *setup1;
  GtkWidget *setup1_menu;
  GtkAccelGroup *setup1_menu_accels;
  GtkWidget *general1;
  GtkWidget *screen_capture1;
  GtkWidget *font_type1;
  GtkWidget *language1;
  GtkWidget *separator21;
  GtkWidget *hardware1;
  GtkWidget *calculator1;
  GtkWidget *advanced1;
  GtkWidget *link_speed1;
  GtkWidget *separator22;
  GtkWidget *probe_i_o_ports1;
  GtkWidget *probe_link_cable1;
  GtkWidget *probe_calc_type1;
  GtkWidget *functions1;
  GtkWidget *functions1_menu;
  GtkAccelGroup *functions1_menu_accels;
  GtkWidget *ready____1;
  GtkWidget *terminal___remote1;
  GtkWidget *screenshot1;
  GtkWidget *directory_list1;
  GtkWidget *separator31;
  GtkWidget *send_backup1;
  GtkWidget *receive_backup1;
  GtkWidget *separator32;
  GtkWidget *send_variable1;
  GtkWidget *receive_variable1;
  GtkWidget *functions2;
  GtkWidget *functions2_menu;
  GtkAccelGroup *functions2_menu_accels;
  GtkWidget *send_flash1;
  GtkWidget *send_flash1_menu;
  GtkAccelGroup *send_flash1_menu_accels;
  GtkWidget *send__free__application1;
  GtkWidget *send_operating_system1;
  GtkWidget *receive__free__application1;
  GtkWidget *get_idlist1;
  GtkWidget *separator41;
  GtkWidget *rom_dump1;
  GtkWidget *rom_version1;
  GtkWidget *separator42;
  GtkWidget *install_a_shell1;
  GtkWidget *plug_ins1;
  GtkWidget *plug_ins1_menu;
  GtkAccelGroup *plug_ins1_menu_accels;
  GtkWidget *options1;
  GtkWidget *load_list1;
  GtkWidget *list1;
  GtkWidget *associations1;
  GtkWidget *misc1;
  GtkWidget *misc1_menu;
  GtkAccelGroup *misc1_menu_accels;
  GtkWidget *register_files1;
  GtkWidget *unregister_files1;
  GtkWidget *separator61;
  GtkWidget *external_programs1;
  GtkWidget *help2;
  GtkWidget *help2_menu;
  GtkAccelGroup *help2_menu_accels;
  GtkWidget *help3;
  GtkWidget *manpage1;
  GtkWidget *separator72;
  GtkWidget *changelog1;
  GtkWidget *separator71;
  GtkWidget *thanks1;
  GtkWidget *about1;
  GtkWidget *handlebox2;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *button12;
  GtkWidget *hpaned1;
  GtkWidget *frame2;
  GtkWidget *scrolledwindow1;
  GtkWidget *ctree1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *frame3;
  GtkWidget *scrolledwindow2;
  GtkWidget *clist1;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *frame4;
  GtkWidget *table1;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label12;
  GtkWidget *label16;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  tilp_dbox = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (tilp_dbox), "tilp_dbox", tilp_dbox);
  gtk_window_set_title (GTK_WINDOW (tilp_dbox), _("TiLP ('Ti Linking Program')"));
  gtk_window_set_default_size (GTK_WINDOW (tilp_dbox), 640, 480);
  gtk_window_set_policy (GTK_WINDOW (tilp_dbox), FALSE, TRUE, TRUE);
  gtk_window_set_wmclass (GTK_WINDOW (tilp_dbox), "tilp", "TiLP");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (tilp_dbox), vbox1);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, FALSE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), menubar1);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  convert_old_files1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (convert_old_files1)->child),
                                   _("_Convert old files"));
  gtk_widget_add_accelerator (convert_old_files1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (convert_old_files1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "convert_old_files1", convert_old_files1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (convert_old_files1);
  gtk_container_add (GTK_CONTAINER (file1_menu), convert_old_files1);
  gtk_tooltips_set_tip (tooltips, convert_old_files1, _("Convert the old GtkTiLink files (PAK files) into TIGL files. Obsolete anyways."), NULL);

  convert_flash_to_rom1 = gtk_menu_item_new_with_label (_("Convert  AMS to ROM image"));
  gtk_widget_ref (convert_flash_to_rom1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "convert_flash_to_rom1", convert_flash_to_rom1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (convert_flash_to_rom1);
  gtk_container_add (GTK_CONTAINER (file1_menu), convert_flash_to_rom1);
  gtk_tooltips_set_tip (tooltips, convert_flash_to_rom1, _("Convert a .tib/.9xu/.89u file into a ROM image"), NULL);

  separator73 = gtk_menu_item_new ();
  gtk_widget_ref (separator73);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator73", separator73,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator73);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator73);
  gtk_widget_set_sensitive (separator73, FALSE);

  unzip_archive1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (unzip_archive1)->child),
                                   _("Un_zip archive"));
  gtk_widget_add_accelerator (unzip_archive1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (unzip_archive1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "unzip_archive1", unzip_archive1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unzip_archive1);
  gtk_container_add (GTK_CONTAINER (file1_menu), unzip_archive1);
  gtk_tooltips_set_tip (tooltips, unzip_archive1, _("Unzip an archive"), NULL);

  untar_archive1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (untar_archive1)->child),
                                   _("Un_tar archive"));
  gtk_widget_add_accelerator (untar_archive1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (untar_archive1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "untar_archive1", untar_archive1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (untar_archive1);
  gtk_container_add (GTK_CONTAINER (file1_menu), untar_archive1);
  gtk_tooltips_set_tip (tooltips, untar_archive1, _("Untar (.tgz/.tar.gz) an archive"), NULL);

  separator74 = gtk_menu_item_new ();
  gtk_widget_ref (separator74);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator74", separator74,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator74);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator74);
  gtk_widget_set_sensitive (separator74, FALSE);

  unpack__obsolete_1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (unpack__obsolete_1)->child),
                                   _("Un_pack (obsolete)"));
  gtk_widget_add_accelerator (unpack__obsolete_1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (unpack__obsolete_1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "unpack__obsolete_1", unpack__obsolete_1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unpack__obsolete_1);
  gtk_container_add (GTK_CONTAINER (file1_menu), unpack__obsolete_1);
  gtk_tooltips_set_tip (tooltips, unpack__obsolete_1, _("Explode a PAK file (old GtkTiLink file format) into several files"), NULL);

  group_file_manager1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (group_file_manager1)->child),
                                   _("_Group File Manager"));
  gtk_widget_add_accelerator (group_file_manager1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (group_file_manager1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "group_file_manager1", group_file_manager1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (group_file_manager1);
  gtk_container_add (GTK_CONTAINER (file1_menu), group_file_manager1);
  gtk_tooltips_set_tip (tooltips, group_file_manager1, _("Launch the GFM for merging/splitting group & single files"), NULL);

  separator12 = gtk_menu_item_new ();
  gtk_widget_ref (separator12);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator12", separator12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator12);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator12);
  gtk_widget_set_sensitive (separator12, FALSE);

  save_config1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (save_config1)->child),
                                   _("Save _config"));
  gtk_widget_add_accelerator (save_config1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (save_config1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "save_config1", save_config1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_config1);
  gtk_container_add (GTK_CONTAINER (file1_menu), save_config1);
  gtk_tooltips_set_tip (tooltips, save_config1, _("Save actual setting in a config file (~/.tilp)"), NULL);
  gtk_widget_add_accelerator (save_config1, "activate", accel_group,
                              GDK_S, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  reload_config1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (reload_config1)->child),
                                   _("_Reload config"));
  gtk_widget_add_accelerator (reload_config1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (reload_config1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "reload_config1", reload_config1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reload_config1);
  gtk_container_add (GTK_CONTAINER (file1_menu), reload_config1);
  gtk_tooltips_set_tip (tooltips, reload_config1, _("Load the config file (~/.tilp)"), NULL);
  gtk_widget_add_accelerator (reload_config1, "activate", accel_group,
                              GDK_R, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  default_config1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (default_config1)->child),
                                   _("_Default config"));
  gtk_widget_add_accelerator (default_config1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (default_config1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "default_config1", default_config1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (default_config1);
  gtk_container_add (GTK_CONTAINER (file1_menu), default_config1);
  gtk_tooltips_set_tip (tooltips, default_config1, _("Load default settings"), NULL);
  gtk_widget_add_accelerator (default_config1, "activate", accel_group,
                              GDK_D, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator13 = gtk_menu_item_new ();
  gtk_widget_ref (separator13);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator13", separator13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator13);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator13);
  gtk_widget_set_sensitive (separator13, FALSE);

  quit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (quit1)->child),
                                   _("_Quit"));
  gtk_widget_add_accelerator (quit1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (quit1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "quit1", quit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), quit1);
  gtk_tooltips_set_tip (tooltips, quit1, _("Quit program"), NULL);
  gtk_widget_add_accelerator (quit1, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  setup1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (setup1)->child),
                                   _("_Setup"));
  gtk_widget_add_accelerator (setup1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (setup1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "setup1", setup1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (setup1);
  gtk_container_add (GTK_CONTAINER (menubar1), setup1);

  setup1_menu = gtk_menu_new ();
  gtk_widget_ref (setup1_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "setup1_menu", setup1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (setup1), setup1_menu);
  setup1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (setup1_menu));

  general1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (general1)->child),
                                   _("_General"));
  gtk_widget_add_accelerator (general1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (general1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "general1", general1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (general1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), general1);
  gtk_tooltips_set_tip (tooltips, general1, _("General options"), NULL);

  screen_capture1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screen_capture1)->child),
                                   _("_Screen capture"));
  gtk_widget_add_accelerator (screen_capture1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (screen_capture1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "screen_capture1", screen_capture1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screen_capture1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), screen_capture1);
  gtk_tooltips_set_tip (tooltips, screen_capture1, _("Screen captures options"), NULL);

  font_type1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (font_type1)->child),
                                   _("_Font type"));
  gtk_widget_add_accelerator (font_type1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (font_type1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "font_type1", font_type1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (font_type1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), font_type1);
  gtk_tooltips_set_tip (tooltips, font_type1, _("Allow you to customize the font of the right windows"), NULL);

  language1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (language1)->child),
                                   _("_Language"));
  gtk_widget_add_accelerator (language1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (language1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "language1", language1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (language1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), language1);
  gtk_tooltips_set_tip (tooltips, language1, _("Allow you to override the default localisation ('C' locale most of the time) for choosing a particular language"), NULL);

  separator21 = gtk_menu_item_new ();
  gtk_widget_ref (separator21);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator21", separator21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator21);
  gtk_container_add (GTK_CONTAINER (setup1_menu), separator21);
  gtk_widget_set_sensitive (separator21, FALSE);

  hardware1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (hardware1)->child),
                                   _("_Hardware"));
  gtk_widget_add_accelerator (hardware1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (hardware1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "hardware1", hardware1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hardware1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), hardware1);
  gtk_tooltips_set_tip (tooltips, hardware1, _("Link cable type, I/O ports or device and kernel drivers"), NULL);

  calculator1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (calculator1)->child),
                                   _("_Calculator"));
  gtk_widget_add_accelerator (calculator1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (calculator1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "calculator1", calculator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (calculator1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), calculator1);
  gtk_tooltips_set_tip (tooltips, calculator1, _("The calculator type to use"), NULL);

  advanced1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (advanced1)->child),
                                   _("_Advanced"));
  gtk_widget_add_accelerator (advanced1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (advanced1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "advanced1", advanced1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (advanced1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), advanced1);

  link_speed1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (link_speed1)->child),
                                   _("_Link speed"));
  gtk_widget_add_accelerator (link_speed1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (link_speed1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "link_speed1", link_speed1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (link_speed1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), link_speed1);
  gtk_tooltips_set_tip (tooltips, link_speed1, _("Baud-rate settings for the fastAVRlink cable only"), NULL);

  separator22 = gtk_menu_item_new ();
  gtk_widget_ref (separator22);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator22", separator22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator22);
  gtk_container_add (GTK_CONTAINER (setup1_menu), separator22);
  gtk_widget_set_sensitive (separator22, FALSE);

  probe_i_o_ports1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (probe_i_o_ports1)->child),
                                   _("Probe _I/O ports"));
  gtk_widget_add_accelerator (probe_i_o_ports1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (probe_i_o_ports1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "probe_i_o_ports1", probe_i_o_ports1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (probe_i_o_ports1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), probe_i_o_ports1);
  gtk_tooltips_set_tip (tooltips, probe_i_o_ports1, _("Probe/auto-detect available I/O ports"), NULL);

  probe_link_cable1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (probe_link_cable1)->child),
                                   _("Probe _link cable"));
  gtk_widget_add_accelerator (probe_link_cable1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (probe_link_cable1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "probe_link_cable1", probe_link_cable1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (probe_link_cable1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), probe_link_cable1);
  gtk_tooltips_set_tip (tooltips, probe_link_cable1, _("Probe/auto-detect your link cable type"), NULL);

  probe_calc_type1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (probe_calc_type1)->child),
                                   _("Probe _calc type"));
  gtk_widget_add_accelerator (probe_calc_type1, "activate_item", setup1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (probe_calc_type1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "probe_calc_type1", probe_calc_type1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (probe_calc_type1);
  gtk_container_add (GTK_CONTAINER (setup1_menu), probe_calc_type1);
  gtk_tooltips_set_tip (tooltips, probe_calc_type1, _("Probe calculator type"), NULL);

  functions1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (functions1)->child),
                                   _("Functions_1"));
  gtk_widget_add_accelerator (functions1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (functions1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "functions1", functions1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (functions1);
  gtk_container_add (GTK_CONTAINER (menubar1), functions1);

  functions1_menu = gtk_menu_new ();
  gtk_widget_ref (functions1_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "functions1_menu", functions1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (functions1), functions1_menu);
  functions1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (functions1_menu));

  ready____1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (ready____1)->child),
                                   _("_Ready ???"));
  gtk_widget_add_accelerator (ready____1, "activate_item", functions1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (ready____1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "ready____1", ready____1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ready____1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), ready____1);
  gtk_tooltips_set_tip (tooltips, ready____1, _("Chech whether your calc is ready"), NULL);

  terminal___remote1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (terminal___remote1)->child),
                                   _("_Terminal & Remote"));
  gtk_widget_add_accelerator (terminal___remote1, "activate_item", functions1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (terminal___remote1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "terminal___remote1", terminal___remote1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (terminal___remote1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), terminal___remote1);
  gtk_tooltips_set_tip (tooltips, terminal___remote1, _("Teminal box and remote control"), NULL);

  screenshot1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (screenshot1)->child),
                                   _("_Screenshot"));
  gtk_widget_add_accelerator (screenshot1, "activate_item", functions1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (screenshot1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "screenshot1", screenshot1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (screenshot1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), screenshot1);
  gtk_tooltips_set_tip (tooltips, screenshot1, _("Screenshot of the calculator screen"), NULL);

  directory_list1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (directory_list1)->child),
                                   _("_Directory list"));
  gtk_widget_add_accelerator (directory_list1, "activate_item", functions1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (directory_list1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "directory_list1", directory_list1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (directory_list1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), directory_list1);
  gtk_tooltips_set_tip (tooltips, directory_list1, _("Do a directory listing of your calculator content"), NULL);

  separator31 = gtk_menu_item_new ();
  gtk_widget_ref (separator31);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator31", separator31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator31);
  gtk_container_add (GTK_CONTAINER (functions1_menu), separator31);
  gtk_widget_set_sensitive (separator31, FALSE);

  send_backup1 = gtk_menu_item_new_with_label (_("Send backup..."));
  gtk_widget_ref (send_backup1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "send_backup1", send_backup1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (send_backup1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), send_backup1);
  gtk_tooltips_set_tip (tooltips, send_backup1, _("Send a backup to your calculator"), NULL);

  receive_backup1 = gtk_menu_item_new_with_label (_("Receive backup"));
  gtk_widget_ref (receive_backup1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "receive_backup1", receive_backup1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (receive_backup1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), receive_backup1);
  gtk_tooltips_set_tip (tooltips, receive_backup1, _("Receive a backup from your calculator"), NULL);

  separator32 = gtk_menu_item_new ();
  gtk_widget_ref (separator32);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator32", separator32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator32);
  gtk_container_add (GTK_CONTAINER (functions1_menu), separator32);
  gtk_widget_set_sensitive (separator32, FALSE);

  send_variable1 = gtk_menu_item_new_with_label (_("Send variable..."));
  gtk_widget_ref (send_variable1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "send_variable1", send_variable1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (send_variable1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), send_variable1);
  gtk_tooltips_set_tip (tooltips, send_variable1, _("Send one variable on your calculator"), NULL);

  receive_variable1 = gtk_menu_item_new_with_label (_("Receive variable"));
  gtk_widget_ref (receive_variable1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "receive_variable1", receive_variable1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (receive_variable1);
  gtk_container_add (GTK_CONTAINER (functions1_menu), receive_variable1);
  gtk_tooltips_set_tip (tooltips, receive_variable1, _("Receive some selected variable(s) from the calculator"), NULL);

  functions2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (functions2)->child),
                                   _("Functions_2"));
  gtk_widget_add_accelerator (functions2, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (functions2);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "functions2", functions2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (functions2);
  gtk_container_add (GTK_CONTAINER (menubar1), functions2);

  functions2_menu = gtk_menu_new ();
  gtk_widget_ref (functions2_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "functions2_menu", functions2_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (functions2), functions2_menu);
  functions2_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (functions2_menu));

  send_flash1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (send_flash1)->child),
                                   _("_Send FLASH"));
  gtk_widget_add_accelerator (send_flash1, "activate_item", functions2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (send_flash1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "send_flash1", send_flash1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (send_flash1);
  gtk_container_add (GTK_CONTAINER (functions2_menu), send_flash1);
  gtk_tooltips_set_tip (tooltips, send_flash1, _("Send a FLASH file"), NULL);

  send_flash1_menu = gtk_menu_new ();
  gtk_widget_ref (send_flash1_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "send_flash1_menu", send_flash1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (send_flash1), send_flash1_menu);
  send_flash1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (send_flash1_menu));

  send__free__application1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (send__free__application1)->child),
                                   _("Send (free) _application"));
  gtk_widget_add_accelerator (send__free__application1, "activate_item", send_flash1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (send__free__application1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "send__free__application1", send__free__application1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (send__free__application1);
  gtk_container_add (GTK_CONTAINER (send_flash1_menu), send__free__application1);
  gtk_tooltips_set_tip (tooltips, send__free__application1, _("Send a FLASH application (only free applications, no certificate)"), NULL);

  send_operating_system1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (send_operating_system1)->child),
                                   _("Send _Operating System"));
  gtk_widget_add_accelerator (send_operating_system1, "activate_item", send_flash1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (send_operating_system1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "send_operating_system1", send_operating_system1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (send_operating_system1);
  gtk_container_add (GTK_CONTAINER (send_flash1_menu), send_operating_system1);
  gtk_tooltips_set_tip (tooltips, send_operating_system1, _("Send an operating system (Advanced Mathematic Software)"), NULL);

  receive__free__application1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (receive__free__application1)->child),
                                   _("_Receive (free) application"));
  gtk_widget_add_accelerator (receive__free__application1, "activate_item", functions2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (receive__free__application1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "receive__free__application1", receive__free__application1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (receive__free__application1);
  gtk_container_add (GTK_CONTAINER (functions2_menu), receive__free__application1);
  gtk_tooltips_set_tip (tooltips, receive__free__application1, _("Receive a free FLASH application from the calculator"), NULL);

  get_idlist1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (get_idlist1)->child),
                                   _("Get _IDlist"));
  gtk_widget_add_accelerator (get_idlist1, "activate_item", functions2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (get_idlist1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "get_idlist1", get_idlist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (get_idlist1);
  gtk_container_add (GTK_CONTAINER (functions2_menu), get_idlist1);
  gtk_tooltips_set_tip (tooltips, get_idlist1, _("Get the ID list of the calculator (if upgraded)"), NULL);

  separator41 = gtk_menu_item_new ();
  gtk_widget_ref (separator41);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator41", separator41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator41);
  gtk_container_add (GTK_CONTAINER (functions2_menu), separator41);
  gtk_widget_set_sensitive (separator41, FALSE);

  rom_dump1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (rom_dump1)->child),
                                   _("ROM _dump..."));
  gtk_widget_add_accelerator (rom_dump1, "activate_item", functions2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (rom_dump1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "rom_dump1", rom_dump1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rom_dump1);
  gtk_container_add (GTK_CONTAINER (functions2_menu), rom_dump1);
  gtk_tooltips_set_tip (tooltips, rom_dump1, _("Do a ROM dump"), NULL);

  rom_version1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (rom_version1)->child),
                                   _("ROM _version"));
  gtk_widget_add_accelerator (rom_version1, "activate_item", functions2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (rom_version1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "rom_version1", rom_version1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rom_version1);
  gtk_container_add (GTK_CONTAINER (functions2_menu), rom_version1);
  gtk_tooltips_set_tip (tooltips, rom_version1, _("Get ROM version"), NULL);

  separator42 = gtk_menu_item_new ();
  gtk_widget_ref (separator42);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator42", separator42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator42);
  gtk_container_add (GTK_CONTAINER (functions2_menu), separator42);
  gtk_widget_set_sensitive (separator42, FALSE);

  install_a_shell1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (install_a_shell1)->child),
                                   _("Install a s_hell"));
  gtk_widget_add_accelerator (install_a_shell1, "activate_item", functions2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (install_a_shell1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "install_a_shell1", install_a_shell1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (install_a_shell1);
  gtk_container_add (GTK_CONTAINER (functions2_menu), install_a_shell1);
  gtk_tooltips_set_tip (tooltips, install_a_shell1, _("Install a shell via TiFFEP"), NULL);

  plug_ins1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (plug_ins1)->child),
                                   _("_Plug-ins"));
  gtk_widget_add_accelerator (plug_ins1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (plug_ins1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "plug_ins1", plug_ins1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (plug_ins1);
  gtk_container_add (GTK_CONTAINER (menubar1), plug_ins1);

  plug_ins1_menu = gtk_menu_new ();
  gtk_widget_ref (plug_ins1_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "plug_ins1_menu", plug_ins1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (plug_ins1), plug_ins1_menu);
  plug_ins1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (plug_ins1_menu));

  options1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (options1)->child),
                                   _("_Options"));
  gtk_widget_add_accelerator (options1, "activate_item", plug_ins1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (plug_ins1_menu), options1);

  load_list1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (load_list1)->child),
                                   _("_Load list"));
  gtk_widget_add_accelerator (load_list1, "activate_item", plug_ins1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (load_list1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "load_list1", load_list1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load_list1);
  gtk_container_add (GTK_CONTAINER (plug_ins1_menu), load_list1);

  list1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (list1)->child),
                                   _("Lis_t..."));
  gtk_widget_add_accelerator (list1, "activate_item", plug_ins1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (list1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "list1", list1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list1);
  gtk_container_add (GTK_CONTAINER (plug_ins1_menu), list1);

  associations1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (associations1)->child),
                                   _("_Associations"));
  gtk_widget_add_accelerator (associations1, "activate_item", plug_ins1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (associations1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "associations1", associations1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (associations1);
  gtk_container_add (GTK_CONTAINER (plug_ins1_menu), associations1);

  misc1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (misc1)->child),
                                   _("_Misc"));
  gtk_widget_add_accelerator (misc1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (misc1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "misc1", misc1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (misc1);
  gtk_container_add (GTK_CONTAINER (menubar1), misc1);

  misc1_menu = gtk_menu_new ();
  gtk_widget_ref (misc1_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "misc1_menu", misc1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (misc1), misc1_menu);
  misc1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (misc1_menu));

  register_files1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (register_files1)->child),
                                   _("_Register files"));
  gtk_widget_add_accelerator (register_files1, "activate_item", misc1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (register_files1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "register_files1", register_files1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (register_files1);
  gtk_container_add (GTK_CONTAINER (misc1_menu), register_files1);
  gtk_tooltips_set_tip (tooltips, register_files1, _("Register file types in the Windows registry (Win32 only)"), NULL);

  unregister_files1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (unregister_files1)->child),
                                   _("_Unregister files"));
  gtk_widget_add_accelerator (unregister_files1, "activate_item", misc1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (unregister_files1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "unregister_files1", unregister_files1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unregister_files1);
  gtk_container_add (GTK_CONTAINER (misc1_menu), unregister_files1);
  gtk_tooltips_set_tip (tooltips, unregister_files1, _("Unregister file types of the Windows registry (Win32 only)"), NULL);

  separator61 = gtk_menu_item_new ();
  gtk_widget_ref (separator61);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator61", separator61,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator61);
  gtk_container_add (GTK_CONTAINER (misc1_menu), separator61);
  gtk_widget_set_sensitive (separator61, FALSE);

  external_programs1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (external_programs1)->child),
                                   _("_External programs"));
  gtk_widget_add_accelerator (external_programs1, "activate_item", misc1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (external_programs1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "external_programs1", external_programs1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (external_programs1);
  gtk_container_add (GTK_CONTAINER (misc1_menu), external_programs1);
  gtk_tooltips_set_tip (tooltips, external_programs1, _("Location of the external programs"), NULL);

  help2 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help2)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help2, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (help2);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "help2", help2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help2);
  gtk_container_add (GTK_CONTAINER (menubar1), help2);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help2));

  help2_menu = gtk_menu_new ();
  gtk_widget_ref (help2_menu);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "help2_menu", help2_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help2), help2_menu);
  help2_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help2_menu));

  help3 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help3)->child),
                                   _("_Help !!!"));
  gtk_widget_add_accelerator (help3, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (help3);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "help3", help3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help3);
  gtk_container_add (GTK_CONTAINER (help2_menu), help3);
  gtk_tooltips_set_tip (tooltips, help3, _("The help file"), NULL);
  gtk_widget_add_accelerator (help3, "activate", accel_group,
                              GDK_H, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  manpage1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (manpage1)->child),
                                   _("_Manpage"));
  gtk_widget_add_accelerator (manpage1, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (manpage1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "manpage1", manpage1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (manpage1);
  gtk_container_add (GTK_CONTAINER (help2_menu), manpage1);
  gtk_tooltips_set_tip (tooltips, manpage1, _("The Linux manual page but also useful for other platforms"), NULL);
  gtk_widget_add_accelerator (manpage1, "activate", accel_group,
                              GDK_M, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separator72 = gtk_menu_item_new ();
  gtk_widget_ref (separator72);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator72", separator72,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator72);
  gtk_container_add (GTK_CONTAINER (help2_menu), separator72);
  gtk_widget_set_sensitive (separator72, FALSE);

  changelog1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (changelog1)->child),
                                   _("_ChangeLog"));
  gtk_widget_add_accelerator (changelog1, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (changelog1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "changelog1", changelog1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (changelog1);
  gtk_container_add (GTK_CONTAINER (help2_menu), changelog1);
  gtk_tooltips_set_tip (tooltips, changelog1, _("The CHANGELOG file"), NULL);

  separator71 = gtk_menu_item_new ();
  gtk_widget_ref (separator71);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "separator71", separator71,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator71);
  gtk_container_add (GTK_CONTAINER (help2_menu), separator71);
  gtk_widget_set_sensitive (separator71, FALSE);

  thanks1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (thanks1)->child),
                                   _("_Thanks"));
  gtk_widget_add_accelerator (thanks1, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (thanks1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "thanks1", thanks1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (thanks1);
  gtk_container_add (GTK_CONTAINER (help2_menu), thanks1);
  gtk_tooltips_set_tip (tooltips, thanks1, _("Some special thanks"), NULL);

  about1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about1)->child),
                                   _("_About"));
  gtk_widget_add_accelerator (about1, "activate_item", help2_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help2_menu), about1);
  gtk_tooltips_set_tip (tooltips, about1, _("Some informations"), NULL);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox2);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "handlebox2", handlebox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar1);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar1), GTK_RELIEF_HALF);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "zzz.xpm");
  button4 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Ready ?"),
                                _("Is calculator ready ?"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "screen2.xpm");
  button5 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Screen"),
                                _("Do a screen capture"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "dirlist.xpm");
  button6 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Dirlist"),
                                _("Directory list of the calculator content"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "memory.xpm");
  button7 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Backup"),
                                _("Backup the calculator content"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "memory.xpm");
  button8 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Restore"),
                                _("Restore the calculator content"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "calc.xpm");
  button9 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("<-/->"),
                                _("Send/Receive variable(s)"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "directory2.xpm");
  button10 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("MkDir"),
                                _("Create a new directory"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button10);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button10", button10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button10);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "empty_trash.xpm");
  button11 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Trash"),
                                _("Delete selected files"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);

  tmp_toolbar_icon = create_pixmap (tilp_dbox, "refresh.xpm");
  button12 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Refresh"),
                                _("Refresh the right window"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (button12);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "button12", button12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button12);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_handle_size (GTK_PANED (hpaned1), 8);
  // Added !!!
  gtk_paned_set_position(GTK_PANED(hpaned1), 290);

  frame2 = gtk_frame_new (_("Calculator files"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_container_add (GTK_CONTAINER (hpaned1), frame2);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame2), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  ctree1 = gtk_ctree_new (4, 0);
  gtk_widget_ref (ctree1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "ctree1", ctree1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ctree1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), ctree1);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 0, 121);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 1, 31);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 2, 38);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 3, 40);
  gtk_clist_set_selection_mode (GTK_CLIST (ctree1), GTK_SELECTION_MULTIPLE);
  gtk_clist_column_titles_show (GTK_CLIST (ctree1));

  label1 = gtk_label_new (_("Varname"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 0, label1);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label2 = gtk_label_new (_("Attr"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 1, label2);

  label3 = gtk_label_new (_("Type"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 2, label3);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_("Size"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 3, label4);
  gtk_widget_set_usize (label4, 20, -2);
  gtk_misc_set_alignment (GTK_MISC (label4), 1, 0.5);

  frame3 = gtk_frame_new (_("Computer files"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_container_add (GTK_CONTAINER (hpaned1), frame3);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (frame3), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist1 = gtk_clist_new (7);
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 16);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 114);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 53);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 5, 81);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 6, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (clist1), GTK_SELECTION_MULTIPLE);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label5 = gtk_label_new (_("|"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label5);

  label6 = gtk_label_new (_("Filename"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label6);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label7 = gtk_label_new (_("Date"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label7);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  label8 = gtk_label_new (_("Size"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label8);
  gtk_misc_set_alignment (GTK_MISC (label8), 1, 0.5);

  label9 = gtk_label_new (_("User"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label9);

  label10 = gtk_label_new (_("Group"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 5, label10);

  label11 = gtk_label_new (_("Attributes"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 6, label11);
  gtk_misc_set_alignment (GTK_MISC (label11), 1, 0.5);

  frame4 = gtk_frame_new (_("Informations"));
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox1), frame4, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);
  gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_ETCHED_OUT);

  table1 = gtk_table_new (4, 2, TRUE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame4), table1);

  label13 = gtk_label_new (_("Number of folders: 0"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("Number of vars: 0"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table1), label14, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("Memory used: 0"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label17 = gtk_label_new (_("Number of directories: 0"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table1), label17, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("Number of files: 0"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table1), label18, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Space used: 0"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table1), label19, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label12 = gtk_label_new (_("Current folder: none"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label16 = gtk_label_new (_("Current dir: none"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table1), label16, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (tilp_dbox), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show),
                      tilp_dbox);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "destroy",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_destroy),
                      tilp_dbox);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_clist1),
                      clist1);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_ctree1),
                      ctree1);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label12),
                      label12);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label13),
                      label13);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label14),
                      label14);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label15),
                      label15);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label16),
                      label16);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label17),
                      label17);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label18),
                      label18);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_label19),
                      label19);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button4),
                      button4);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button5),
                      button5);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button6),
                      button6);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button7),
                      button7);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button8),
                      button8);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button9),
                      button9);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button10),
                      button10);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button11),
                      button11);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_button12),
                      button12);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_frame2),
                      scrolledwindow1);
  gtk_signal_connect (GTK_OBJECT (tilp_dbox), "show",
                      GTK_SIGNAL_FUNC (on_tilp_dbox_show_sb),
                      statusbar1);
  gtk_signal_connect (GTK_OBJECT (convert_old_files1), "activate",
                      GTK_SIGNAL_FUNC (on_convert_old_files1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (convert_flash_to_rom1), "activate",
                      GTK_SIGNAL_FUNC (on_convert_flash_to_rom1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unzip_archive1), "activate",
                      GTK_SIGNAL_FUNC (on_unzip_archive1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (untar_archive1), "activate",
                      GTK_SIGNAL_FUNC (on_untar_archive1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unpack__obsolete_1), "activate",
                      GTK_SIGNAL_FUNC (on_unpack__obsolete_1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (group_file_manager1), "activate",
                      GTK_SIGNAL_FUNC (on_group_file_manager1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save_config1), "activate",
                      GTK_SIGNAL_FUNC (on_save_config1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reload_config1), "activate",
                      GTK_SIGNAL_FUNC (on_reload_config1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (default_config1), "activate",
                      GTK_SIGNAL_FUNC (on_default_config1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit1), "activate",
                      GTK_SIGNAL_FUNC (on_quit1_activate),
                      tilp_dbox);
  gtk_signal_connect (GTK_OBJECT (general1), "activate",
                      GTK_SIGNAL_FUNC (on_general1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screen_capture1), "activate",
                      GTK_SIGNAL_FUNC (on_screen_capture1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (font_type1), "activate",
                      GTK_SIGNAL_FUNC (on_font_type1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (language1), "activate",
                      GTK_SIGNAL_FUNC (on_language1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hardware1), "activate",
                      GTK_SIGNAL_FUNC (on_hardware1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (calculator1), "activate",
                      GTK_SIGNAL_FUNC (on_calculator1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (advanced1), "activate",
                      GTK_SIGNAL_FUNC (on_advanced1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (link_speed1), "activate",
                      GTK_SIGNAL_FUNC (on_link_speed1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (probe_i_o_ports1), "activate",
                      GTK_SIGNAL_FUNC (on_probe_i_o_ports1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (probe_link_cable1), "activate",
                      GTK_SIGNAL_FUNC (on_probe_link_cable1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (probe_calc_type1), "activate",
                      GTK_SIGNAL_FUNC (on_probe_calc_type1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ready____1), "activate",
                      GTK_SIGNAL_FUNC (on_ready____1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (terminal___remote1), "activate",
                      GTK_SIGNAL_FUNC (on_terminal___remote1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (screenshot1), "activate",
                      GTK_SIGNAL_FUNC (on_screenshot1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (directory_list1), "activate",
                      GTK_SIGNAL_FUNC (on_directory_list1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (send_backup1), "activate",
                      GTK_SIGNAL_FUNC (on_send_backup1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (receive_backup1), "activate",
                      GTK_SIGNAL_FUNC (on_receive_backup1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (send_variable1), "activate",
                      GTK_SIGNAL_FUNC (on_send_variable1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (receive_variable1), "activate",
                      GTK_SIGNAL_FUNC (on_receive_variable1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (send__free__application1), "activate",
                      GTK_SIGNAL_FUNC (on_send__free__application1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (send_operating_system1), "activate",
                      GTK_SIGNAL_FUNC (on_send_operating_system1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (receive__free__application1), "activate",
                      GTK_SIGNAL_FUNC (on_receive__free__application1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (get_idlist1), "activate",
                      GTK_SIGNAL_FUNC (on_get_idlist1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rom_dump1), "activate",
                      GTK_SIGNAL_FUNC (on_rom_dump1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rom_version1), "activate",
                      GTK_SIGNAL_FUNC (on_rom_version1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (install_a_shell1), "activate",
                      GTK_SIGNAL_FUNC (on_install_a_shell1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (options1), "activate",
                      GTK_SIGNAL_FUNC (on_options1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load_list1), "activate",
                      GTK_SIGNAL_FUNC (on_load_list1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (list1), "activate",
                      GTK_SIGNAL_FUNC (on_list1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (associations1), "activate",
                      GTK_SIGNAL_FUNC (on_associations1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (register_files1), "activate",
                      GTK_SIGNAL_FUNC (on_register_files1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unregister_files1), "activate",
                      GTK_SIGNAL_FUNC (on_unregister_files1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (external_programs1), "activate",
                      GTK_SIGNAL_FUNC (on_external_programs1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (help3), "activate",
                      GTK_SIGNAL_FUNC (on_help2_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (manpage1), "activate",
                      GTK_SIGNAL_FUNC (on_manpage1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (changelog1), "activate",
                      GTK_SIGNAL_FUNC (on_changelog1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (thanks1), "activate",
                      GTK_SIGNAL_FUNC (on_thanks1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button4_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button5_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button6_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button7_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button8_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button9_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button10), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button10_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button11), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button11_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button12), "clicked",
                      GTK_SIGNAL_FUNC (on_tilp_button12_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "click_column",
                      GTK_SIGNAL_FUNC (on_ctree1_click_column),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "button_press_event",
                      GTK_SIGNAL_FUNC (on_ctree1_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "tree_expand",
                      GTK_SIGNAL_FUNC (on_ctree1_tree_expand),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "tree_collapse",
                      GTK_SIGNAL_FUNC (on_ctree1_tree_collapse),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "tree_select_row",
                      GTK_SIGNAL_FUNC (on_ctree1_tree_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "tree_unselect_row",
                      GTK_SIGNAL_FUNC (on_ctree1_tree_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "click_column",
                      GTK_SIGNAL_FUNC (on_tilp_clist1_click_column),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "select_row",
                      GTK_SIGNAL_FUNC (on_tilp_clist1_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "unselect_row",
                      GTK_SIGNAL_FUNC (on_tilp_clist1_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "button_press_event",
                      GTK_SIGNAL_FUNC (on_tilp_clist1_button_press_event),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (tilp_dbox), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (tilp_dbox), accel_group);

  return tilp_dbox;
}

