/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_pbar1_dbox (void);
GtkWidget* create_pbar2_dbox (void);
GtkWidget* create_pbar3_dbox (void);
GtkWidget* create_pbar4_dbox (void);
GtkWidget* create_pbar5_dbox (void);
