/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <stdio.h>

#include "interface.h"
#include "support.h"

#include "tilp_plugin.h"
#include <tilp/tifiles.h>

TilpPluginInfo infos = 
{
  "Number Viewer/Editor",
  "1.0.0",
  "Romain Lievin <roms@lpg.ticalc.org>",
  "82n,83n"
};

GtkWidget *dialog1;
TiRegular  content;

/* 
   Returns plug-ins properties/capabilites 
   - name [out]    : the plug-in name
   - version [out] : the plug-in version
   - fext [out]    : an array of file extensions
*/
TilpPluginInfo* plugin_query(void)
{
  return &infos;
}

/* Run plug-in */
int plugin_run(void)
{  
  dialog1 = create_dialog1 ();
  gtk_widget_show (dialog1);

  //gtk_main ();

  return 0;
}

/* Load file */
int plugin_load(const char *filename)
{
  gint i;
  gint err;

  err = ti8x_read_regular_file(filename, &content);
  if(err)
    {
      g_error("read error !\n");
      return -1;
    }

  for(i=0; i<content.num_entries; i++)
    {
      //      TiVarEntry *entry = &(content.entries[i]);;
      
      
    }

  return 0;
}

/* Save file */
int plugin_save(const char *filename)
{
  printf(" plugin_save\n");
  return 0;
}

int
main (int argc, char *argv[])
{
  GtkWidget *dialog1;

#ifdef ENABLE_NLS
  bindtextdomain(PLUGIN, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset(PACKAGE, "UTF-8");
  textdomain(PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  //add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");
  //add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  dialog1 = create_dialog1 ();
  gtk_widget_show (dialog1);

  gtk_main ();
  return 0;
}

