/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_calc_cb.h"
#include "gtk_calc_dbox.h"
#include "support.h"

GtkWidget*
create_calctype_dbox (void)
{
  GtkWidget *calctype_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *table1;
  GSList *calc_group_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton9;
  GtkWidget *radiobutton8;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton7;
  GtkWidget *checkbutton1;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *ok_button;
  GtkWidget *hbox2;
  GtkWidget *pixmap2;
  guint label2_key;
  GtkWidget *label2;
  GtkWidget *cancel_button;
  GtkWidget *hbox1;
  GtkWidget *pixmap1;
  guint label1_key;
  GtkWidget *label1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  calctype_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (calctype_dbox), "calctype_dbox", calctype_dbox);
  gtk_window_set_title (GTK_WINDOW (calctype_dbox), _("Choose your calculator type"));
  gtk_window_set_policy (GTK_WINDOW (calctype_dbox), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (calctype_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (calctype_dbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (_("Calculator type:"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  table1 = gtk_table_new (3, 3, TRUE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame1), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);

  radiobutton1 = gtk_radio_button_new_with_label (calc_group_group, _("TI92+"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton1));
  gtk_widget_ref (radiobutton1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton1", radiobutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton1);
  gtk_table_attach (GTK_TABLE (table1), radiobutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton3 = gtk_radio_button_new_with_label (calc_group_group, _("TI89"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton3));
  gtk_widget_ref (radiobutton3);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton3", radiobutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton3);
  gtk_table_attach (GTK_TABLE (table1), radiobutton3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton6 = gtk_radio_button_new_with_label (calc_group_group, _("TI83+"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton6));
  gtk_widget_ref (radiobutton6);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton6", radiobutton6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton6);
  gtk_table_attach (GTK_TABLE (table1), radiobutton6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton9 = gtk_radio_button_new_with_label (calc_group_group, _("TI73"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton9));
  gtk_widget_ref (radiobutton9);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton9", radiobutton9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton9);
  gtk_table_attach (GTK_TABLE (table1), radiobutton9, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton8 = gtk_radio_button_new_with_label (calc_group_group, _("TI82"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton8));
  gtk_widget_ref (radiobutton8);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton8", radiobutton8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton8);
  gtk_table_attach (GTK_TABLE (table1), radiobutton8, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton5 = gtk_radio_button_new_with_label (calc_group_group, _("TI85"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton5));
  gtk_widget_ref (radiobutton5);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton5", radiobutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton5);
  gtk_table_attach (GTK_TABLE (table1), radiobutton5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton2 = gtk_radio_button_new_with_label (calc_group_group, _("TI92"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton2));
  gtk_widget_ref (radiobutton2);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton2", radiobutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton2);
  gtk_table_attach (GTK_TABLE (table1), radiobutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton2), TRUE);

  radiobutton4 = gtk_radio_button_new_with_label (calc_group_group, _("TI86"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton4));
  gtk_widget_ref (radiobutton4);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton4", radiobutton4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton4);
  gtk_table_attach (GTK_TABLE (table1), radiobutton4, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton7 = gtk_radio_button_new_with_label (calc_group_group, _("TI83"));
  calc_group_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton7));
  gtk_widget_ref (radiobutton7);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "radiobutton7", radiobutton7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton7);
  gtk_table_attach (GTK_TABLE (table1), radiobutton7, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton1 = gtk_check_button_new_with_label (_("Auto-detect (89/92/92+)"));
  gtk_widget_ref (checkbutton1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "checkbutton1", checkbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (vbox1), checkbutton1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (checkbutton1), 5);

  dialog_action_area1 = GTK_DIALOG (calctype_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (calctype_dbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  ok_button = gtk_button_new ();
  gtk_widget_ref (ok_button);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "ok_button", ok_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (ok_button), hbox2);

  pixmap2 = create_pixmap (calctype_dbox, "yes.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, FALSE, 0);

  label2 = gtk_label_new ("");
  label2_key = gtk_label_parse_uline (GTK_LABEL (label2),
                                   _("_OK"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  cancel_button = gtk_button_new ();
  gtk_widget_ref (cancel_button);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "cancel_button", cancel_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (cancel_button), hbox1);

  pixmap1 = create_pixmap (calctype_dbox, "no.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap1, TRUE, FALSE, 0);

  label1 = gtk_label_new ("");
  label1_key = gtk_label_parse_uline (GTK_LABEL (label1),
                                   _("_Cancel"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (calctype_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show1),
                      radiobutton1);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show2),
                      radiobutton2);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show3),
                      radiobutton3);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show4),
                      radiobutton4);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show5),
                      radiobutton5);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show6),
                      radiobutton6);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show7),
                      radiobutton7);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show8),
                      radiobutton8);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show9),
                      radiobutton9);
  gtk_signal_connect (GTK_OBJECT (calctype_dbox), "show",
                      GTK_SIGNAL_FUNC (on_calctype_dbox_show10),
                      checkbutton1);
  gtk_signal_connect (GTK_OBJECT (radiobutton1), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton1_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton3), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton3_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton6), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton6_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton9), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton9_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton8), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton8_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton5), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton5_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton2), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton2_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton4), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton4_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (radiobutton7), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton7_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton1), "toggled",
                      GTK_SIGNAL_FUNC (calctype_on_checkbutton1_toggled),
                      checkbutton1);
  gtk_signal_connect (GTK_OBJECT (ok_button), "clicked",
                      GTK_SIGNAL_FUNC (on_ok_button_clicked),
                      calctype_dbox);
  gtk_signal_connect (GTK_OBJECT (cancel_button), "clicked",
                      GTK_SIGNAL_FUNC (on_cancel_button_clicked),
                      calctype_dbox);

  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              label2_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              label1_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (calctype_dbox), accel_group);

  return calctype_dbox;
}

