/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_lang_cb.h"
#include "gtk_lang_dbox.h"
#include "support.h"

GtkWidget*
create_lang_dbox (void)
{
  GtkWidget *lang_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *frame4;
  GtkWidget *hbox4;
  GtkWidget *label8;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *combo_entry1;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *ok_button;
  GtkWidget *hbox3;
  GtkWidget *pixmap2;
  guint label7_key;
  GtkWidget *label7;
  GtkWidget *cancel_button;
  GtkWidget *hbox2;
  GtkWidget *pixmap1;
  guint label6_key;
  GtkWidget *label6;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  lang_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (lang_dbox), "lang_dbox", lang_dbox);
  gtk_window_set_title (GTK_WINDOW (lang_dbox), _("Configuration of the link cable and I/O ports"));
  gtk_window_set_policy (GTK_WINDOW (lang_dbox), FALSE, TRUE, TRUE);

  dialog_vbox1 = GTK_DIALOG (lang_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (lang_dbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  frame4 = gtk_frame_new (_("Language type:"));
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), frame4, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);

  hbox4 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (frame4), hbox4);

  label8 = gtk_label_new (_("Locale:"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox4), label8, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 5, 0);

  combo1 = gtk_combo_new ();
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (hbox4), combo1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (combo1), 5);
  combo1_items = g_list_append (combo1_items, _("C"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_entry_set_text (GTK_ENTRY (combo_entry1), _("C"));

  dialog_action_area1 = GTK_DIALOG (lang_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (lang_dbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  ok_button = gtk_button_new ();
  gtk_widget_ref (ok_button);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "ok_button", ok_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (ok_button), hbox3);

  pixmap2 = create_pixmap (lang_dbox, "yes.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox3), pixmap2, TRUE, FALSE, 0);

  label7 = gtk_label_new ("");
  label7_key = gtk_label_parse_uline (GTK_LABEL (label7),
                                   _("_OK"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 5, 0);

  cancel_button = gtk_button_new ();
  gtk_widget_ref (cancel_button);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "cancel_button", cancel_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (cancel_button), hbox2);

  pixmap1 = create_pixmap (lang_dbox, "no.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap1, TRUE, FALSE, 0);

  label6 = gtk_label_new ("");
  label6_key = gtk_label_parse_uline (GTK_LABEL (label6),
                                   _("_Cancel"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (lang_dbox), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, TRUE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  gtk_signal_connect (GTK_OBJECT (lang_dbox), "show",
                      GTK_SIGNAL_FUNC (on_lang_dbox_show),
                      lang_dbox);
  gtk_signal_connect (GTK_OBJECT (lang_dbox), "show",
                      GTK_SIGNAL_FUNC (on_lang_dbox_show3),
                      combo1);
  gtk_signal_connect (GTK_OBJECT (lang_dbox), "show",
                      GTK_SIGNAL_FUNC (on_lang_dbox_show2),
                      combo_entry1);
  gtk_signal_connect (GTK_OBJECT (combo_entry1), "changed",
                      GTK_SIGNAL_FUNC (on_lang_combo_entry1_changed),
                      combo_entry1);
  gtk_signal_connect (GTK_OBJECT (ok_button), "clicked",
                      GTK_SIGNAL_FUNC (lang_ok_button_clicked),
                      lang_dbox);
  gtk_signal_connect (GTK_OBJECT (cancel_button), "clicked",
                      GTK_SIGNAL_FUNC (lang_cancel_button_clicked),
                      lang_dbox);

  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              label7_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              label6_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (lang_dbox), accel_group);

  return lang_dbox;
}

