/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_pbar_cb.h"
#include "gtk_pbar_dbox.h"
#include "support.h"

GtkWidget*
create_pbar1_dbox (void)
{
  GtkWidget *pbar1_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *label10;
  GtkWidget *progressbar1;
  GtkWidget *hseparator1;
  GtkWidget *label20;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *hbox1;
  GtkWidget *pixmap1;
  GtkWidget *label1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pbar1_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (pbar1_dbox), "pbar1_dbox", pbar1_dbox);
  gtk_window_set_title (GTK_WINDOW (pbar1_dbox), _("Title1"));
  gtk_window_set_position (GTK_WINDOW (pbar1_dbox), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (pbar1_dbox), TRUE);

  dialog_vbox1 = GTK_DIALOG (pbar1_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (pbar1_dbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 5);

  label10 = gtk_label_new (_("Transfer status:"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (vbox1), label10, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  progressbar1 = gtk_progress_bar_new ();
  gtk_widget_ref (progressbar1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "progressbar1", progressbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progressbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), progressbar1, FALSE, FALSE, 0);
  gtk_progress_bar_set_bar_style (GTK_PROGRESS_BAR (progressbar1), GTK_PROGRESS_DISCRETE);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, TRUE, TRUE, 5);

  label20 = gtk_label_new (_("Rate: 0.00 Kb/s"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (vbox1), label20, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  dialog_action_area1 = GTK_DIALOG (pbar1_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (pbar1_dbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  button1 = gtk_button_new ();
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (button1), hbox1);

  pixmap1 = create_pixmap (pbar1_dbox, "no.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap1, TRUE, FALSE, 0);

  label1 = gtk_label_new (_("Abort"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (pbar1_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  gtk_signal_connect (GTK_OBJECT (pbar1_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar1_dbox_show1),
                      pbar1_dbox);
  gtk_signal_connect (GTK_OBJECT (pbar1_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_pbar1),
                      progressbar1);
  gtk_signal_connect (GTK_OBJECT (pbar1_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_rate),
                      label20);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (pbar1_ok_button_clicked),
                      pbar1_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (pbar1_dbox), accel_group);

  return pbar1_dbox;
}

GtkWidget*
create_pbar2_dbox (void)
{
  GtkWidget *pbar2_dbox;
  GtkWidget *dialog_vbox2;
  GtkWidget *label3;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox2;
  GtkWidget *button2;
  GtkWidget *hbox2;
  GtkWidget *pixmap2;
  GtkWidget *label4;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pbar2_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (pbar2_dbox), "pbar2_dbox", pbar2_dbox);
  gtk_window_set_title (GTK_WINDOW (pbar2_dbox), _("Title2"));
  gtk_window_set_position (GTK_WINDOW (pbar2_dbox), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (pbar2_dbox), TRUE);

  dialog_vbox2 = GTK_DIALOG (pbar2_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (pbar2_dbox), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  label3 = gtk_label_new (_("Message."));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (pbar2_dbox), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 5);

  dialog_action_area2 = GTK_DIALOG (pbar2_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (pbar2_dbox), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (pbar2_dbox), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbuttonbox2, TRUE, TRUE, 0);

  button2 = gtk_button_new ();
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (pbar2_dbox), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button2, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (pbar2_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (button2), hbox2);

  pixmap2 = create_pixmap (pbar2_dbox, "no.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (pbar2_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, FALSE, 0);

  label4 = gtk_label_new (_("Abort"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (pbar2_dbox), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 5, 0);

  gtk_signal_connect (GTK_OBJECT (pbar2_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar1_dbox_show1),
                      pbar2_dbox);
  gtk_signal_connect (GTK_OBJECT (pbar2_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_label1),
                      label3);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (pbar1_ok_button_clicked),
                      pbar2_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (pbar2_dbox), accel_group);

  return pbar2_dbox;
}

GtkWidget*
create_pbar3_dbox (void)
{
  GtkWidget *pbar3_dbox;
  GtkWidget *dialog_vbox3;
  GtkWidget *vbox2;
  GtkWidget *label11;
  GtkWidget *progressbar2;
  GtkWidget *label12;
  GtkWidget *progressbar3;
  GtkWidget *hseparator2;
  GtkWidget *label21;
  GtkWidget *dialog_action_area3;
  GtkWidget *hbuttonbox3;
  GtkWidget *button4;
  GtkWidget *hbox4;
  GtkWidget *pixmap4;
  GtkWidget *label7;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pbar3_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (pbar3_dbox), "pbar3_dbox", pbar3_dbox);
  gtk_window_set_title (GTK_WINDOW (pbar3_dbox), _("Title3"));
  gtk_window_set_position (GTK_WINDOW (pbar3_dbox), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (pbar3_dbox), TRUE);

  dialog_vbox3 = GTK_DIALOG (pbar3_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (pbar3_dbox), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), vbox2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  label11 = gtk_label_new (_("Total transfer:"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (vbox2), label11, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  progressbar2 = gtk_progress_bar_new ();
  gtk_widget_ref (progressbar2);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "progressbar2", progressbar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progressbar2);
  gtk_box_pack_start (GTK_BOX (vbox2), progressbar2, FALSE, FALSE, 0);
  gtk_progress_set_show_text (GTK_PROGRESS (progressbar2), TRUE);

  label12 = gtk_label_new (_("Current transfer:"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (vbox2), label12, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  progressbar3 = gtk_progress_bar_new ();
  gtk_widget_ref (progressbar3);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "progressbar3", progressbar3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progressbar3);
  gtk_box_pack_start (GTK_BOX (vbox2), progressbar3, FALSE, FALSE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator2, TRUE, TRUE, 5);

  label21 = gtk_label_new (_("Rate: 0.0 Kbytes/s"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (vbox2), label21, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  dialog_action_area3 = GTK_DIALOG (pbar3_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (pbar3_dbox), "dialog_action_area3", dialog_action_area3);
  gtk_widget_show (dialog_action_area3);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area3), 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (dialog_action_area3), hbuttonbox3, TRUE, TRUE, 0);

  button4 = gtk_button_new ();
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button4, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (button4), hbox4);

  pixmap4 = create_pixmap (pbar3_dbox, "no.xpm");
  gtk_widget_ref (pixmap4);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "pixmap4", pixmap4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap4);
  gtk_box_pack_start (GTK_BOX (hbox4), pixmap4, TRUE, FALSE, 0);

  label7 = gtk_label_new (_("Abort"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (pbar3_dbox), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 5, 0);

  gtk_signal_connect (GTK_OBJECT (pbar3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar1_dbox_show1),
                      pbar3_dbox);
  gtk_signal_connect (GTK_OBJECT (pbar3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_pbar1),
                      progressbar3);
  gtk_signal_connect (GTK_OBJECT (pbar3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_pbar2),
                      progressbar2);
  gtk_signal_connect (GTK_OBJECT (pbar3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_rate),
                      label21);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (pbar1_ok_button_clicked),
                      pbar3_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (pbar3_dbox), accel_group);

  return pbar3_dbox;
}

GtkWidget*
create_pbar4_dbox (void)
{
  GtkWidget *pbar4_dbox;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox3;
  GtkWidget *label14;
  GtkWidget *progressbar4;
  GtkWidget *label15;
  GtkWidget *hseparator3;
  GtkWidget *label22;
  GtkWidget *dialog_action_area4;
  GtkWidget *button5;
  GtkWidget *hbox5;
  GtkWidget *pixmap5;
  GtkWidget *label13;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pbar4_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (pbar4_dbox), "pbar4_dbox", pbar4_dbox);
  gtk_window_set_title (GTK_WINDOW (pbar4_dbox), _("Title4"));
  gtk_window_set_position (GTK_WINDOW (pbar4_dbox), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (pbar4_dbox), TRUE);

  dialog_vbox4 = GTK_DIALOG (pbar4_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (pbar4_dbox), "dialog_vbox4", dialog_vbox4);
  gtk_widget_show (dialog_vbox4);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 5);

  label14 = gtk_label_new (_("Current transfer:"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (vbox3), label14, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  progressbar4 = gtk_progress_bar_new ();
  gtk_widget_ref (progressbar4);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "progressbar4", progressbar4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progressbar4);
  gtk_box_pack_start (GTK_BOX (vbox3), progressbar4, FALSE, FALSE, 0);
  gtk_progress_bar_set_bar_style (GTK_PROGRESS_BAR (progressbar4), GTK_PROGRESS_DISCRETE);

  label15 = gtk_label_new (_("Text"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (vbox3), label15, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label15), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label15), 0, 5);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator3);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "hseparator3", hseparator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator3, TRUE, TRUE, 5);

  label22 = gtk_label_new (_("Rate: 0.0 Kbytes/s"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (vbox3), label22, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  dialog_action_area4 = GTK_DIALOG (pbar4_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (pbar4_dbox), "dialog_action_area4", dialog_action_area4);
  gtk_widget_show (dialog_action_area4);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area4), 10);

  button5 = gtk_button_new ();
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (dialog_action_area4), button5, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button5, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (button5), hbox5);

  pixmap5 = create_pixmap (pbar4_dbox, "no.xpm");
  gtk_widget_ref (pixmap5);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "pixmap5", pixmap5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap5);
  gtk_box_pack_start (GTK_BOX (hbox5), pixmap5, TRUE, FALSE, 0);

  label13 = gtk_label_new (_("Abort"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (pbar4_dbox), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox5), label13, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label13), 5, 0);

  gtk_signal_connect (GTK_OBJECT (pbar4_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar1_dbox_show1),
                      pbar4_dbox);
  gtk_signal_connect (GTK_OBJECT (pbar4_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_pbar1),
                      progressbar4);
  gtk_signal_connect (GTK_OBJECT (pbar4_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_label1),
                      label15);
  gtk_signal_connect (GTK_OBJECT (pbar4_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_rate),
                      label22);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (pbar1_ok_button_clicked),
                      pbar4_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (pbar4_dbox), accel_group);

  return pbar4_dbox;
}

GtkWidget*
create_pbar5_dbox (void)
{
  GtkWidget *pbar5_dbox;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox4;
  GtkWidget *label17;
  GtkWidget *progressbar5;
  GtkWidget *label18;
  GtkWidget *progressbar6;
  GtkWidget *label19;
  GtkWidget *hseparator4;
  GtkWidget *label23;
  GtkWidget *dialog_action_area5;
  GtkWidget *hbuttonbox4;
  GtkWidget *button6;
  GtkWidget *hbox6;
  GtkWidget *pixmap6;
  GtkWidget *label16;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  pbar5_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (pbar5_dbox), "pbar5_dbox", pbar5_dbox);
  gtk_window_set_title (GTK_WINDOW (pbar5_dbox), _("Title5"));
  gtk_window_set_position (GTK_WINDOW (pbar5_dbox), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (pbar5_dbox), TRUE);

  dialog_vbox5 = GTK_DIALOG (pbar5_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (pbar5_dbox), "dialog_vbox5", dialog_vbox5);
  gtk_widget_show (dialog_vbox5);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 5);

  label17 = gtk_label_new (_("Total transfer:"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (vbox4), label17, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  progressbar5 = gtk_progress_bar_new ();
  gtk_widget_ref (progressbar5);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "progressbar5", progressbar5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progressbar5);
  gtk_box_pack_start (GTK_BOX (vbox4), progressbar5, FALSE, FALSE, 0);
  gtk_progress_bar_set_bar_style (GTK_PROGRESS_BAR (progressbar5), GTK_PROGRESS_DISCRETE);
  gtk_progress_set_show_text (GTK_PROGRESS (progressbar5), TRUE);

  label18 = gtk_label_new (_("Current transfer:"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (vbox4), label18, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  progressbar6 = gtk_progress_bar_new ();
  gtk_widget_ref (progressbar6);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "progressbar6", progressbar6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progressbar6);
  gtk_box_pack_start (GTK_BOX (vbox4), progressbar6, FALSE, FALSE, 0);
  gtk_progress_bar_set_bar_style (GTK_PROGRESS_BAR (progressbar6), GTK_PROGRESS_DISCRETE);

  label19 = gtk_label_new (_("Text"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (vbox4), label19, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label19), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label19), 0, 5);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator4);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "hseparator4", hseparator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator4, TRUE, TRUE, 5);

  label23 = gtk_label_new (_("Rate: 0.0 Kbytes/s"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox4), label23, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  dialog_action_area5 = GTK_DIALOG (pbar5_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (pbar5_dbox), "dialog_action_area5", dialog_action_area5);
  gtk_widget_show (dialog_action_area5);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area5), 10);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (dialog_action_area5), hbuttonbox4, TRUE, TRUE, 0);

  button6 = gtk_button_new ();
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button6, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (button6), hbox6);

  pixmap6 = create_pixmap (pbar5_dbox, "no.xpm");
  gtk_widget_ref (pixmap6);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "pixmap6", pixmap6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap6);
  gtk_box_pack_start (GTK_BOX (hbox6), pixmap6, TRUE, FALSE, 0);

  label16 = gtk_label_new (_("Abort"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (pbar5_dbox), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox6), label16, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label16), 5, 0);

  gtk_signal_connect (GTK_OBJECT (pbar5_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar1_dbox_show1),
                      pbar5_dbox);
  gtk_signal_connect (GTK_OBJECT (pbar5_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_pbar1),
                      progressbar6);
  gtk_signal_connect (GTK_OBJECT (pbar5_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_pbar2),
                      progressbar5);
  gtk_signal_connect (GTK_OBJECT (pbar5_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_label1),
                      label19);
  gtk_signal_connect (GTK_OBJECT (pbar5_dbox), "show",
                      GTK_SIGNAL_FUNC (on_pbar_dbox_show_rate),
                      label23);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (pbar1_ok_button_clicked),
                      pbar5_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (pbar5_dbox), accel_group);

  return pbar5_dbox;
}

