/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_general_cb.h"
#include "gtk_general_dbox.h"
#include "support.h"

GtkWidget*
create_general_dbox (void)
{
  GtkWidget *general_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *table1;
  GtkWidget *frame1;
  GtkWidget *label3;
  GtkWidget *frame2;
  GtkWidget *label4;
  GtkWidget *frame4;
  GtkWidget *hbox4;
  GSList *group2_group = NULL;
  GtkWidget *radiobutton21;
  GtkWidget *radiobutton22;
  GtkWidget *frame5;
  GtkWidget *hbox3;
  GSList *group1_group = NULL;
  GtkWidget *radiobutton11;
  GtkWidget *radiobutton12;
  GtkWidget *frame6;
  GtkWidget *table3;
  GSList *group3_group = NULL;
  GtkWidget *radiobutton31;
  GtkWidget *radiobutton32;
  GtkWidget *radiobutton33;
  GtkWidget *radiobutton34;
  GtkWidget *frame7;
  GtkWidget *hbox5;
  GSList *group4_group = NULL;
  GtkWidget *radiobutton41;
  GtkWidget *radiobutton42;
  GtkWidget *frame9;
  GtkWidget *checkbutton1;
  GtkWidget *frame11;
  GtkWidget *table4;
  GSList *group6_group = NULL;
  GtkWidget *radiobutton61;
  GtkWidget *radiobutton62;
  GtkWidget *radiobutton63;
  GtkWidget *radiobutton66;
  GtkWidget *radiobutton65;
  GtkWidget *radiobutton64;
  GtkWidget *frame12;
  GtkWidget *hbox6;
  GSList *group7_group = NULL;
  GtkWidget *radiobutton71;
  GtkWidget *radiobutton72;
  GtkWidget *frame3;
  GtkWidget *table2;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *vseparator1;
  GtkWidget *frame8;
  GtkWidget *hbox7;
  GSList *group5_group = NULL;
  GtkWidget *radiobutton51;
  GtkWidget *radiobutton52;
  GtkWidget *frame10;
  GtkWidget *checkbutton2;
  GtkWidget *frame13;
  GtkWidget *hbox8;
  GtkWidget *label7;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *combo_entry1;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *ok_button;
  GtkWidget *hbox2;
  GtkWidget *pixmap2;
  guint label2_key;
  GtkWidget *label2;
  GtkWidget *cancel_button;
  GtkWidget *hbox1;
  GtkWidget *pixmap1;
  guint label1_key;
  GtkWidget *label1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  general_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (general_dbox), "general_dbox", general_dbox);
  gtk_window_set_title (GTK_WINDOW (general_dbox), _("General options"));
  gtk_window_set_policy (GTK_WINDOW (general_dbox), FALSE, FALSE, TRUE);

  dialog_vbox1 = GTK_DIALOG (general_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (general_dbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  table1 = gtk_table_new (7, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_table_attach (GTK_TABLE (table1), frame1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label3 = gtk_label_new (_("Left Window"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (frame1), label3);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_table_attach (GTK_TABLE (table1), frame2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label4 = gtk_label_new (_("Right Window"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (frame2), label4);

  frame4 = gtk_frame_new (_("Path mode"));
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_table_attach (GTK_TABLE (table1), frame4, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (frame4), hbox4);

  radiobutton21 = gtk_radio_button_new_with_label (group2_group, _("Full path"));
  group2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton21));
  gtk_widget_ref (radiobutton21);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton21", radiobutton21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton21);
  gtk_box_pack_start (GTK_BOX (hbox4), radiobutton21, TRUE, TRUE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton21), TRUE);

  radiobutton22 = gtk_radio_button_new_with_label (group2_group, _("Local path"));
  group2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton22));
  gtk_widget_ref (radiobutton22);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton22", radiobutton22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton22);
  gtk_box_pack_start (GTK_BOX (hbox4), radiobutton22, TRUE, TRUE, 0);

  frame5 = gtk_frame_new (_("Transfer mode"));
  gtk_widget_ref (frame5);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame5", frame5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame5);
  gtk_table_attach (GTK_TABLE (table1), frame5, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (frame5), hbox3);

  radiobutton11 = gtk_radio_button_new_with_label (group1_group, _("Silent"));
  group1_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton11));
  gtk_widget_ref (radiobutton11);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton11", radiobutton11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton11);
  gtk_box_pack_start (GTK_BOX (hbox3), radiobutton11, TRUE, TRUE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton11), TRUE);

  radiobutton12 = gtk_radio_button_new_with_label (group1_group, _("Manual"));
  group1_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton12));
  gtk_widget_ref (radiobutton12);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton12", radiobutton12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton12);
  gtk_box_pack_start (GTK_BOX (hbox3), radiobutton12, TRUE, TRUE, 0);

  frame6 = gtk_frame_new (_("Sort by"));
  gtk_widget_ref (frame6);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame6", frame6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame6);
  gtk_table_attach (GTK_TABLE (table1), frame6, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  table3 = gtk_table_new (2, 2, TRUE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame6), table3);

  radiobutton31 = gtk_radio_button_new_with_label (group3_group, _("name"));
  group3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton31));
  gtk_widget_ref (radiobutton31);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton31", radiobutton31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton31);
  gtk_table_attach (GTK_TABLE (table3), radiobutton31, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton31), TRUE);

  radiobutton32 = gtk_radio_button_new_with_label (group3_group, _("type"));
  group3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton32));
  gtk_widget_ref (radiobutton32);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton32", radiobutton32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton32);
  gtk_table_attach (GTK_TABLE (table3), radiobutton32, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton33 = gtk_radio_button_new_with_label (group3_group, _("info"));
  group3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton33));
  gtk_widget_ref (radiobutton33);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton33", radiobutton33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton33);
  gtk_table_attach (GTK_TABLE (table3), radiobutton33, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton34 = gtk_radio_button_new_with_label (group3_group, _("size"));
  group3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton34));
  gtk_widget_ref (radiobutton34);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton34", radiobutton34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton34);
  gtk_table_attach (GTK_TABLE (table3), radiobutton34, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  frame7 = gtk_frame_new (_("Order"));
  gtk_widget_ref (frame7);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame7", frame7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame7);
  gtk_table_attach (GTK_TABLE (table1), frame7, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox5 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (frame7), hbox5);

  radiobutton41 = gtk_radio_button_new_with_label (group4_group, _("increasing"));
  group4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton41));
  gtk_widget_ref (radiobutton41);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton41", radiobutton41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton41);
  gtk_box_pack_start (GTK_BOX (hbox5), radiobutton41, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton41), TRUE);

  radiobutton42 = gtk_radio_button_new_with_label (group4_group, _("decreasing"));
  group4_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton42));
  gtk_widget_ref (radiobutton42);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton42", radiobutton42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton42);
  gtk_box_pack_start (GTK_BOX (hbox5), radiobutton42, FALSE, FALSE, 0);

  frame9 = gtk_frame_new (_("Extended file format (89/92+)"));
  gtk_widget_ref (frame9);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame9", frame9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame9);
  gtk_table_attach (GTK_TABLE (table1), frame9, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  checkbutton1 = gtk_check_button_new_with_label (_("Keep archive attribute"));
  gtk_widget_ref (checkbutton1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "checkbutton1", checkbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton1);
  gtk_container_add (GTK_CONTAINER (frame9), checkbutton1);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton1), TRUE);

  frame11 = gtk_frame_new (_("Sort by"));
  gtk_widget_ref (frame11);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame11", frame11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame11);
  gtk_table_attach (GTK_TABLE (table1), frame11, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  table4 = gtk_table_new (2, 3, FALSE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame11), table4);

  radiobutton61 = gtk_radio_button_new_with_label (group6_group, _("name"));
  group6_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton61));
  gtk_widget_ref (radiobutton61);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton61", radiobutton61,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton61);
  gtk_table_attach (GTK_TABLE (table4), radiobutton61, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton61), TRUE);

  radiobutton62 = gtk_radio_button_new_with_label (group6_group, _("size"));
  group6_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton62));
  gtk_widget_ref (radiobutton62);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton62", radiobutton62,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton62);
  gtk_table_attach (GTK_TABLE (table4), radiobutton62, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton63 = gtk_radio_button_new_with_label (group6_group, _("group"));
  group6_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton63));
  gtk_widget_ref (radiobutton63);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton63", radiobutton63,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton63);
  gtk_table_attach (GTK_TABLE (table4), radiobutton63, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton66 = gtk_radio_button_new_with_label (group6_group, _("user"));
  group6_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton66));
  gtk_widget_ref (radiobutton66);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton66", radiobutton66,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton66);
  gtk_table_attach (GTK_TABLE (table4), radiobutton66, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton65 = gtk_radio_button_new_with_label (group6_group, _("attributes"));
  group6_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton65));
  gtk_widget_ref (radiobutton65);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton65", radiobutton65,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton65);
  gtk_table_attach (GTK_TABLE (table4), radiobutton65, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  radiobutton64 = gtk_radio_button_new_with_label (group6_group, _("date"));
  group6_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton64));
  gtk_widget_ref (radiobutton64);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton64", radiobutton64,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton64);
  gtk_table_attach (GTK_TABLE (table4), radiobutton64, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  frame12 = gtk_frame_new (_("Order"));
  gtk_widget_ref (frame12);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame12", frame12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame12);
  gtk_table_attach (GTK_TABLE (table1), frame12, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox6 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (frame12), hbox6);

  radiobutton71 = gtk_radio_button_new_with_label (group7_group, _("increasing"));
  group7_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton71));
  gtk_widget_ref (radiobutton71);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton71", radiobutton71,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton71);
  gtk_box_pack_start (GTK_BOX (hbox6), radiobutton71, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton71), TRUE);

  radiobutton72 = gtk_radio_button_new_with_label (group7_group, _("decreasing"));
  group7_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton72));
  gtk_widget_ref (radiobutton72);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton72", radiobutton72,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton72);
  gtk_box_pack_start (GTK_BOX (hbox6), radiobutton72, FALSE, FALSE, 0);

  frame3 = gtk_frame_new (_("Window size"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_table_attach (GTK_TABLE (table1), frame3, 0, 1, 1, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  table2 = gtk_table_new (2, 3, TRUE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (frame3), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 2);

  label5 = gtk_label_new (_("Width:"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new (_("Height:"));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  spinbutton1_adj = gtk_adjustment_new (300, 1, 1500, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_ref (spinbutton1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "spinbutton1", spinbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton1);
  gtk_table_attach (GTK_TABLE (table2), spinbutton1, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton2_adj = gtk_adjustment_new (400, 1, 1500, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_ref (spinbutton2);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "spinbutton2", spinbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton2);
  gtk_table_attach (GTK_TABLE (table2), spinbutton2, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "vseparator1", vseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator1);
  gtk_table_attach (GTK_TABLE (table2), vseparator1, 1, 2, 0, 2,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  frame8 = gtk_frame_new (_("Hidden files"));
  gtk_widget_ref (frame8);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame8", frame8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame8);
  gtk_table_attach (GTK_TABLE (table1), frame8, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox7 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (frame8), hbox7);

  radiobutton51 = gtk_radio_button_new_with_label (group5_group, _("Show"));
  group5_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton51));
  gtk_widget_ref (radiobutton51);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton51", radiobutton51,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton51);
  gtk_box_pack_start (GTK_BOX (hbox7), radiobutton51, TRUE, TRUE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton51), TRUE);

  radiobutton52 = gtk_radio_button_new_with_label (group5_group, _("Hide"));
  group5_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton52));
  gtk_widget_ref (radiobutton52);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "radiobutton52", radiobutton52,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton52);
  gtk_box_pack_start (GTK_BOX (hbox7), radiobutton52, TRUE, TRUE, 0);

  frame10 = gtk_frame_new (_("Files"));
  gtk_widget_ref (frame10);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame10", frame10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame10);
  gtk_table_attach (GTK_TABLE (table1), frame10, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  checkbutton2 = gtk_check_button_new_with_label (_("Confirm deleting/overwriting"));
  gtk_widget_ref (checkbutton2);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "checkbutton2", checkbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton2);
  gtk_container_add (GTK_CONTAINER (frame10), checkbutton2);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton2), TRUE);

  frame13 = gtk_frame_new (_("File type checking"));
  gtk_widget_ref (frame13);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "frame13", frame13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame13);
  gtk_table_attach (GTK_TABLE (table1), frame13, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (frame13), hbox8);

  label7 = gtk_label_new (_("Security level:"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox8), label7, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 5, 0);

  combo1 = gtk_combo_new ();
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (hbox8), combo1, FALSE, FALSE, 5);
  gtk_combo_set_value_in_list (GTK_COMBO (combo1), TRUE, FALSE);
  combo1_items = g_list_append (combo1_items, _("none"));
  combo1_items = g_list_append (combo1_items, _("middle"));
  combo1_items = g_list_append (combo1_items, _("restrictive"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_widget_set_usize (combo_entry1, 75, -2);
  gtk_entry_set_editable (GTK_ENTRY (combo_entry1), FALSE);
  gtk_entry_set_text (GTK_ENTRY (combo_entry1), _("middle"));

  dialog_action_area1 = GTK_DIALOG (general_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (general_dbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  ok_button = gtk_button_new ();
  gtk_widget_ref (ok_button);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "ok_button", ok_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ok_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), ok_button);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (ok_button), hbox2);

  pixmap2 = create_pixmap (general_dbox, "yes.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, FALSE, 0);

  label2 = gtk_label_new ("");
  label2_key = gtk_label_parse_uline (GTK_LABEL (label2),
                                   _("_OK"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  cancel_button = gtk_button_new ();
  gtk_widget_ref (cancel_button);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "cancel_button", cancel_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cancel_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), cancel_button);
  GTK_WIDGET_SET_FLAGS (cancel_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (cancel_button), hbox1);

  pixmap1 = create_pixmap (general_dbox, "no.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap1, TRUE, FALSE, 0);

  label1 = gtk_label_new ("");
  label1_key = gtk_label_parse_uline (GTK_LABEL (label1),
                                   _("_Cancel"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (general_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show),
                      general_dbox);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show2),
                      spinbutton1);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show3),
                      spinbutton2);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show4),
                      radiobutton11);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show5),
                      radiobutton12);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show6),
                      radiobutton21);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show7),
                      radiobutton22);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show8),
                      radiobutton31);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show9),
                      radiobutton32);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show10),
                      radiobutton33);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show11),
                      radiobutton34);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show12),
                      radiobutton41);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show13),
                      radiobutton42);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show14),
                      radiobutton51);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show15),
                      radiobutton52);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show16),
                      checkbutton1);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show17),
                      checkbutton2);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show18),
                      radiobutton61);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show19),
                      radiobutton62);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show20),
                      radiobutton63);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show21),
                      radiobutton64);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show22),
                      radiobutton65);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show23),
                      radiobutton66);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show24),
                      radiobutton71);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show25),
                      radiobutton72);
  gtk_signal_connect (GTK_OBJECT (general_dbox), "show",
                      GTK_SIGNAL_FUNC (on_general_dbox_show26),
                      combo_entry1);
  gtk_signal_connect (GTK_OBJECT (radiobutton21), "toggled",
                      GTK_SIGNAL_FUNC (on_general_radiobutton21_toggled),
                      radiobutton21);
  gtk_signal_connect (GTK_OBJECT (radiobutton22), "toggled",
                      GTK_SIGNAL_FUNC (on_general_radiobutton22_toggled),
                      radiobutton22);
  gtk_signal_connect (GTK_OBJECT (radiobutton11), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton11_toggled),
                      radiobutton11);
  gtk_signal_connect (GTK_OBJECT (radiobutton12), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton12_toggled),
                      radiobutton12);
  gtk_signal_connect (GTK_OBJECT (radiobutton31), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton31_toggled),
                      radiobutton31);
  gtk_signal_connect (GTK_OBJECT (radiobutton32), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton32_toggled),
                      radiobutton32);
  gtk_signal_connect (GTK_OBJECT (radiobutton33), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton33_toggled),
                      radiobutton33);
  gtk_signal_connect (GTK_OBJECT (radiobutton34), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton34_toggled),
                      radiobutton34);
  gtk_signal_connect (GTK_OBJECT (radiobutton41), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton41_toggled),
                      radiobutton41);
  gtk_signal_connect (GTK_OBJECT (radiobutton42), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton42_toggled),
                      radiobutton42);
  gtk_signal_connect (GTK_OBJECT (checkbutton1), "toggled",
                      GTK_SIGNAL_FUNC (on_general_checkbutton1_toggled),
                      checkbutton1);
  gtk_signal_connect (GTK_OBJECT (radiobutton61), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton61_toggled),
                      radiobutton61);
  gtk_signal_connect (GTK_OBJECT (radiobutton62), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton62_toggled),
                      radiobutton62);
  gtk_signal_connect (GTK_OBJECT (radiobutton63), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton63_toggled),
                      radiobutton63);
  gtk_signal_connect (GTK_OBJECT (radiobutton66), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton66_toggled),
                      radiobutton66);
  gtk_signal_connect (GTK_OBJECT (radiobutton65), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton65_toggled),
                      radiobutton65);
  gtk_signal_connect (GTK_OBJECT (radiobutton64), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton64_toggled),
                      radiobutton64);
  gtk_signal_connect (GTK_OBJECT (radiobutton71), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton71_toggled),
                      radiobutton71);
  gtk_signal_connect (GTK_OBJECT (radiobutton72), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton72_toggled),
                      radiobutton72);
  gtk_signal_connect (GTK_OBJECT (spinbutton1), "changed",
                      GTK_SIGNAL_FUNC (on_general_spinbutton1_changed),
                      spinbutton1);
  gtk_signal_connect (GTK_OBJECT (spinbutton2), "changed",
                      GTK_SIGNAL_FUNC (on_spinbutton2_changed),
                      spinbutton2);
  gtk_signal_connect (GTK_OBJECT (radiobutton51), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton51_toggled),
                      radiobutton51);
  gtk_signal_connect (GTK_OBJECT (radiobutton52), "toggled",
                      GTK_SIGNAL_FUNC (on_radiobutton52_toggled),
                      radiobutton52);
  gtk_signal_connect (GTK_OBJECT (checkbutton2), "toggled",
                      GTK_SIGNAL_FUNC (on_general_checkbutton2_toggled),
                      checkbutton2);
  gtk_signal_connect (GTK_OBJECT (combo_entry1), "changed",
                      GTK_SIGNAL_FUNC (on_general_combo_entry1_changed),
                      combo_entry1);
  gtk_signal_connect (GTK_OBJECT (ok_button), "clicked",
                      GTK_SIGNAL_FUNC (on_general_ok_button_clicked),
                      general_dbox);
  gtk_signal_connect (GTK_OBJECT (cancel_button), "clicked",
                      GTK_SIGNAL_FUNC (on_general_cancel_button_clicked),
                      general_dbox);

  gtk_widget_add_accelerator (ok_button, "clicked", accel_group,
                              label2_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (cancel_button, "clicked", accel_group,
                              label1_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (general_dbox), accel_group);

  return general_dbox;
}

