/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_user_cb.h"
#include "gtk_user_dbox.h"
#include "support.h"

GtkWidget*
create_user1_dbox (void)
{
  GtkWidget *user1_dbox;
  GtkWidget *dialog_vbox1;
  GtkWidget *label2;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *hbox1;
  GtkWidget *pixmap1;
  GtkWidget *label1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  user1_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (user1_dbox), "user1_dbox", user1_dbox);
  gtk_window_set_title (GTK_WINDOW (user1_dbox), _("Title1"));
  gtk_window_set_modal (GTK_WINDOW (user1_dbox), TRUE);
  gtk_window_set_policy (GTK_WINDOW (user1_dbox), TRUE, TRUE, FALSE);

  dialog_vbox1 = GTK_DIALOG (user1_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (user1_dbox), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label2 = gtk_label_new (_("Message."));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (user1_dbox), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label2), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 5);

  dialog_action_area1 = GTK_DIALOG (user1_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (user1_dbox), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (user1_dbox), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  button1 = gtk_button_new ();
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (user1_dbox), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (button1, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (user1_dbox), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (button1), hbox1);

  pixmap1 = create_pixmap (user1_dbox, "yes.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (user1_dbox), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap1, TRUE, FALSE, 0);

  label1 = gtk_label_new (_("b1"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (user1_dbox), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 5, 0);

  gtk_signal_connect (GTK_OBJECT (user1_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show1),
                      user1_dbox);
  gtk_signal_connect (GTK_OBJECT (user1_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show2),
                      label2);
  gtk_signal_connect (GTK_OBJECT (user1_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show3),
                      label1);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (user1_ok_button_clicked),
                      user1_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (user1_dbox), accel_group);

  return user1_dbox;
}

GtkWidget*
create_user2_dbox (void)
{
  GtkWidget *user2_dbox;
  GtkWidget *dialog_vbox2;
  GtkWidget *label3;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox2;
  GtkWidget *button2;
  GtkWidget *hbox2;
  GtkWidget *pixmap2;
  GtkWidget *label4;
  GtkWidget *button3;
  GtkWidget *hbox3;
  GtkWidget *pixmap3;
  GtkWidget *label5;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  user2_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (user2_dbox), "user2_dbox", user2_dbox);
  gtk_window_set_title (GTK_WINDOW (user2_dbox), _("Title2"));
  gtk_window_set_modal (GTK_WINDOW (user2_dbox), TRUE);
  gtk_window_set_policy (GTK_WINDOW (user2_dbox), TRUE, TRUE, FALSE);

  dialog_vbox2 = GTK_DIALOG (user2_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (user2_dbox), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  label3 = gtk_label_new (_("Message."));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 5);

  dialog_action_area2 = GTK_DIALOG (user2_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (user2_dbox), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbuttonbox2, TRUE, TRUE, 0);

  button2 = gtk_button_new ();
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (button2), hbox2);

  pixmap2 = create_pixmap (user2_dbox, "yes.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, FALSE, 0);

  label4 = gtk_label_new (_("b1"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 5, 0);

  button3 = gtk_button_new ();
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button3, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (button3), hbox3);

  pixmap3 = create_pixmap (user2_dbox, "no.xpm");
  gtk_widget_ref (pixmap3);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "pixmap3", pixmap3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap3);
  gtk_box_pack_start (GTK_BOX (hbox3), pixmap3, TRUE, FALSE, 0);

  label5 = gtk_label_new (_("b2"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (user2_dbox), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  gtk_signal_connect (GTK_OBJECT (user2_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show1),
                      user2_dbox);
  gtk_signal_connect (GTK_OBJECT (user2_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show2),
                      label3);
  gtk_signal_connect (GTK_OBJECT (user2_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show3),
                      label4);
  gtk_signal_connect (GTK_OBJECT (user2_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show4),
                      label5);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (user1_ok_button_clicked),
                      user2_dbox);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (user2_ok_button_clicked),
                      user2_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (user2_dbox), accel_group);

  return user2_dbox;
}

GtkWidget*
create_user3_dbox (void)
{
  GtkWidget *user3_dbox;
  GtkWidget *dialog_vbox3;
  GtkWidget *label6;
  GtkWidget *dialog_action_area3;
  GtkWidget *hbuttonbox3;
  GtkWidget *button4;
  GtkWidget *hbox4;
  GtkWidget *pixmap4;
  GtkWidget *label7;
  GtkWidget *button5;
  GtkWidget *hbox5;
  GtkWidget *pixmap5;
  GtkWidget *label8;
  GtkWidget *button6;
  GtkWidget *hbox6;
  GtkWidget *pixmap6;
  GtkWidget *label9;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  user3_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (user3_dbox), "user3_dbox", user3_dbox);
  gtk_window_set_title (GTK_WINDOW (user3_dbox), _("Title3"));
  gtk_window_set_modal (GTK_WINDOW (user3_dbox), TRUE);
  gtk_window_set_policy (GTK_WINDOW (user3_dbox), TRUE, TRUE, FALSE);

  dialog_vbox3 = GTK_DIALOG (user3_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (user3_dbox), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  label6 = gtk_label_new (_("Message."));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label6), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 5);

  dialog_action_area3 = GTK_DIALOG (user3_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (user3_dbox), "dialog_action_area3", dialog_action_area3);
  gtk_widget_show (dialog_action_area3);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area3), 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (dialog_action_area3), hbuttonbox3, TRUE, TRUE, 0);

  button4 = gtk_button_new ();
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button4, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (button4), hbox4);

  pixmap4 = create_pixmap (user3_dbox, "yes.xpm");
  gtk_widget_ref (pixmap4);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "pixmap4", pixmap4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap4);
  gtk_box_pack_start (GTK_BOX (hbox4), pixmap4, TRUE, FALSE, 0);

  label7 = gtk_label_new (_("b1"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label7), 5, 0);

  button5 = gtk_button_new ();
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button5);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (button5), hbox5);

  pixmap5 = create_pixmap (user3_dbox, "no.xpm");
  gtk_widget_ref (pixmap5);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "pixmap5", pixmap5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap5);
  gtk_box_pack_start (GTK_BOX (hbox5), pixmap5, TRUE, FALSE, 0);

  label8 = gtk_label_new (_("b2"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 5, 0);

  button6 = gtk_button_new ();
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button6, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (button6), hbox6);

  pixmap6 = create_pixmap (user3_dbox, "no.xpm");
  gtk_widget_ref (pixmap6);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "pixmap6", pixmap6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap6);
  gtk_box_pack_start (GTK_BOX (hbox6), pixmap6, TRUE, FALSE, 0);

  label9 = gtk_label_new (_("b3"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (user3_dbox), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox6), label9, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label9), 5, 0);

  gtk_signal_connect (GTK_OBJECT (user3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show1),
                      user3_dbox);
  gtk_signal_connect (GTK_OBJECT (user3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show2),
                      label6);
  gtk_signal_connect (GTK_OBJECT (user3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show3),
                      label7);
  gtk_signal_connect (GTK_OBJECT (user3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show4),
                      label8);
  gtk_signal_connect (GTK_OBJECT (user3_dbox), "show",
                      GTK_SIGNAL_FUNC (on_user1_dbox_show5),
                      label9);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (user1_ok_button_clicked),
                      user3_dbox);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (user2_ok_button_clicked),
                      user3_dbox);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (user3_ok_button_clicked),
                      user3_dbox);

  gtk_window_add_accel_group (GTK_WINDOW (user3_dbox), accel_group);

  return user3_dbox;
}

