/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_entry_cb.h"
#include "gtk_entry_dbox.h"
#include "support.h"

GtkWidget*
create_entry_dbox (void)
{
  GtkWidget *entry_dbox;
  GtkWidget *dialog_vbox2;
  GtkWidget *frame1;
  GtkWidget *vbox1;
  GtkWidget *entry1;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox2;
  GtkWidget *button2;
  GtkWidget *hbox2;
  GtkWidget *pixmap2;
  guint label4_key;
  GtkWidget *label4;
  GtkWidget *button3;
  GtkWidget *hbox3;
  GtkWidget *pixmap3;
  guint label5_key;
  GtkWidget *label5;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  entry_dbox = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (entry_dbox), "entry_dbox", entry_dbox);
  gtk_window_set_title (GTK_WINDOW (entry_dbox), _("Title"));
  gtk_window_set_modal (GTK_WINDOW (entry_dbox), TRUE);
  gtk_window_set_policy (GTK_WINDOW (entry_dbox), TRUE, TRUE, FALSE);

  dialog_vbox2 = GTK_DIALOG (entry_dbox)->vbox;
  gtk_object_set_data (GTK_OBJECT (entry_dbox), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  frame1 = gtk_frame_new (_("Name:"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), frame1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (frame1), vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 5);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (vbox1), entry1, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (entry_dbox)->action_area;
  gtk_object_set_data (GTK_OBJECT (entry_dbox), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbuttonbox2, TRUE, TRUE, 0);

  button2 = gtk_button_new ();
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button2, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (button2), hbox2);

  pixmap2 = create_pixmap (entry_dbox, "yes.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, FALSE, 0);

  label4 = gtk_label_new ("");
  label4_key = gtk_label_parse_uline (GTK_LABEL (label4),
                                   _("_OK"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 5, 0);

  button3 = gtk_button_new ();
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button3, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (button3), hbox3);

  pixmap3 = create_pixmap (entry_dbox, "no.xpm");
  gtk_widget_ref (pixmap3);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "pixmap3", pixmap3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap3);
  gtk_box_pack_start (GTK_BOX (hbox3), pixmap3, TRUE, FALSE, 0);

  label5 = gtk_label_new ("");
  label5_key = gtk_label_parse_uline (GTK_LABEL (label5),
                                   _("_Cancel"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (entry_dbox), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  gtk_signal_connect (GTK_OBJECT (entry_dbox), "show",
                      GTK_SIGNAL_FUNC (on_entry_dbox_show1),
                      entry_dbox);
  gtk_signal_connect (GTK_OBJECT (entry_dbox), "show",
                      GTK_SIGNAL_FUNC (on_entry_dbox_show2),
                      frame1);
  gtk_signal_connect (GTK_OBJECT (entry_dbox), "show",
                      GTK_SIGNAL_FUNC (on_entry_dbox_show3),
                      entry1);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (entry_ok_button_clicked),
                      entry_dbox);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (entry_cancel_button_clicked),
                      entry_dbox);

  gtk_widget_add_accelerator (button2, "clicked", accel_group,
                              label4_key, GDK_MOD1_MASK, 0);
  gtk_widget_add_accelerator (button3, "clicked", accel_group,
                              label5_key, GDK_MOD1_MASK, 0);

  gtk_window_add_accel_group (GTK_WINDOW (entry_dbox), accel_group);

  return entry_dbox;
}

