# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


srcdir = .
top_srcdir = ..

prefix = /usr
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/tilp
pkglibdir = $(libdir)/tilp
pkgincludedir = $(includedir)/tilp

top_builddir = ..

ACLOCAL = aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = automake-1.4
AUTOHEADER = autoheader
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = i686-pc-linux-gnu
ALLOW_EXIT_HOMEDIR = 
AR = ar
AS = as
AWK = mawk
BUILD_INCLUDED_LIBINTL = no
CATOBJEXT = .gmo
CC = gcc
CFLAGS = -g -O2 -I/usr/include/tilp   -I/usr/include/tilp   -I/usr/include/tilp   -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -I/usr/include/libglade-2.0 -I/usr/include/gtk-2.0 -I/usr/include/libxml2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/X11R6/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -D__LINUX__ -Wall
CXX = g++
CXXCPP = g++ -E
DATADIRNAME = share
DLLTOOL = dlltool
ECHO = echo
EGREP = grep -E
EXEEXT = 
F77 = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GENCAT = gencat
GLIBC21 = yes
GLIB_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
GLIB_LIBS = -lglib-2.0  
GMSGFMT = /usr/bin/msgfmt
GTK_CFLAGS = -I/usr/include/libglade-2.0 -I/usr/include/gtk-2.0 -I/usr/include/libxml2 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/X11R6/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
GTK_LIBS = -Wl,--export-dynamic -lglade-2.0 -lgtk-x11-2.0 -lxml2 -lpthread -lz -lgdk-x11-2.0 -latk-1.0 -lgdk_pixbuf-2.0 -lm -lpangoxft-1.0 -lpangox-1.0 -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0  
HAVE_ASPRINTF = 1
HAVE_LIB = @HAVE_LIB@
HAVE_POSIX_PRINTF = 1
HAVE_SNPRINTF = 1
HAVE_WPRINTF = 0
INSTOBJEXT = .mo
INTLBISON = bison
INTLLIBS = 
INTLOBJS = 
INTL_LIBTOOL_SUFFIX_PREFIX = 
LDFLAGS =  -lticables   -ltifiles   -lticalcs -lticables -ltifiles   -lglib-2.0   -Wl,--export-dynamic -lglade-2.0 -lgtk-x11-2.0 -lxml2 -lpthread -lz -lgdk-x11-2.0 -latk-1.0 -lgdk_pixbuf-2.0 -lm -lpangoxft-1.0 -lpangox-1.0 -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0    -g
LIB = @LIB@
LIBICONV = 
LIBINTL = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIB = @LTLIB@
LTLIBICONV = 
LTLIBINTL = 
MAINT = #
MAKEINFO = /home/devel/tilp_project/tilp/missing makeinfo
MKINSTALLDIRS = $(top_builddir)/./mkinstalldirs
OBJDUMP = objdump
OBJEXT = o
PACKAGE = tilp
PKG_CONFIG = /usr/bin/pkg-config
POSUB = po
RANLIB = ranlib
RC = @RC@
STRIP = strip
TICABLES_CFLAGS = -I/usr/include/tilp  
TICABLES_LIBS = -lticables  
TICALCS_CFLAGS = -I/usr/include/tilp  
TICALCS_LIBS = -lticalcs -lticables -ltifiles  
TIFILES_CFLAGS = -I/usr/include/tilp  
TIFILES_LIBS = -ltifiles  
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 6.69
locale_dir = ${prefix}/share/locale
tilp_glade_dir = ${prefix}/share/tilp/glade
tilp_help_dir = ${prefix}/share/tilp/help
tilp_icon_dir = ${prefix}/share/tilp/icons
tilp_pixmap_dir = ${prefix}/share/tilp/pixmaps
tilp_plugin_dir = ${exec_prefix}/lib/tilp

SHELL = /bin/sh
#PREFIX=/usr
SHARE_DIR = $(prefix)/share/tilp
INSTALL = /usr/bin/install -c

EXTRA_DIST = gnome kde others
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu desktop/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = desktop

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu desktop/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


install: $(FILES)
	@echo Installing magic local data for file\(1\) command...
	@if ! grep "\*\*TI85\*\*" /etc/magic; then	\
		cat others/magic >> /etc/magic;		\
	fi;
	@echo Done.

	@echo "---";

	@echo Installing Gnome VFS MIME magic patterns...
	@if ! grep "\*\*TI" /etc/gnome-vfs-mime-magic; then		\
		cat gnome/gnome-vfs-mime-magic >> /etc/gnome-vfs-mime-magic;	\
	fi;

	@echo Installing application registry in Gnome...
	@$(INSTALL) -m644 gnome/tilp.applications /usr/share/application-registry

	@echo Installing file and icons handling in Gnome...
	@$(INSTALL) -m644 gnome/tilp.keys /usr/share/mime-info
	@$(INSTALL) -m644 gnome/tilp.mime /usr/share/mime-info

	@echo Installing TiLP menu entry in Gnome...
	@$(INSTALL) -m644 gnome/TiLP.desktop /usr/share/applications
	@echo Done.

	@echo "---";

	@echo Installing KMimeMagic local data...
	@if ! grep "\*\*TI85" /usr/share/mimelnk/magic; then    \
		cat kde/magic >> /usr/share/mimelnk/magic;      \
	fi;

	@echo Installing TiLP menu entry in KDE...
	@$(INSTALL) -d /usr/share/applnk/Edutainment/Mathematics
	@$(INSTALL) -m644 kde/tilp.desktop /usr/share/applnk/Edutainment/Mathematics/

	@echo Installing file and icons handling in KDE...
	@$(INSTALL) -m644 kde/x-tilp.desktop /usr/share/mimelnk/application
	@echo Done.

uninstall: $(FILES)
	@echo Removing desktop files...
	@echo Done.

dos2unix:
	dos2unix
	lowercase
	uppercase

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
